CREATE TABLE IF NOT EXISTS products (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    cost REAL,
    stock_count REAL,
    product_value REAL,
    stock_category TEXT NOT NULL,
    product_category TEXT NOT NULL,
    sage_code TEXT,
    supplier TEXT,
    sold_as TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS stock_take (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    stock_count TEXT NOT NULL,
    product_category TEXT NOT NULL,
    date_added TEXT DEFAULT CURRENT_TIMESTAMP
);

-- Insert initial product data
INSERT INTO products (name, price, description) VALUES
-- (name, cost, stock_count, product_value, category, sage_code, supplier, sold_as)
('Topside', 0, 0, 0, 'fresh', 'beef', '', '', 'kilo'),
('Silverside', 0, 0, 0, 'fresh', 'beef', '', '', 'kilo'),
('Brisket', 0, 0, 0, 'fresh', 'beef', '', '', 'kilo'),
('Skirts', 0, 0, 0, 'fresh', 'beef', '', '', 'kilo'),
('Frozen 95vl', 0, 0, 0, 'fresh', 'beef', '', '', 'kilo'),
('Fresh 95vl', 0, 0, 0, 'fresh', 'beef', '', '', 'kilo'),
('85vl', 0, 0, 0, 'fresh', 'beef', '', '', 'kilo'),
('Blades', 0, 0, 0, 'fresh', 'beef', '', '', 'kilo'),
('Chuck', 0, 0, 0, 'fresh', 'beef', '', '', 'kilo'),
('Fore Rib', 0, 0, 0, 'fresh', 'beef', '', '', 'kilo'),
('Pressed Fat', 0, 0, 0, 'fresh', 'beef', '', '', 'kilo'),
('Diced Beef', 0, 0, 0, 'fresh', 'beef', '', '', 'kilo'),
('Rump', 0, 0, 0, 'fresh', 'beef', '', '', 'kilo'),
('Fillet', 0, 0, 0, 'fresh', 'beef', '', '', 'kilo'),
('Fillet Tails', 0, 0, 0, 'fresh', 'beef', '', '', 'kilo'),
('Striploins', 0, 0, 0, 'fresh', 'beef', '', '', 'kilo'),
('Nerve Ends', 0, 0, 0, 'fresh', 'beef', '', '', 'kilo'),
('Rleye-UK', 0, 0, 0, 'fresh', 'beef', '', '', 'kilo'),
('8kg + Striploin', 0, 0, 0, 'fresh', 'beef', '', '', 'kilo'),
('Rump Trim', 0, 0, 0, 'fresh', 'beef', '', '', 'kilo'),
('Fat Trim', 0, 0, 0, 'fresh', 'beef', '', '', 'kilo'),
('Burger Mix', 0, 0, 0, 'fresh', 'beef', '', '', 'kilo'),

('Mutton Leg', 0, 0, 0, 'fresh', 'lamb', '', '', 'kilo'),
('Lamb Legs', 0, 0, 0, 'fresh', 'lamb', '', '', 'kilo'),
('Lamb Breasts', 0, 0, 0, 'fresh', 'lamb', '', '', 'kilo'),
('Lamb Saddles', 0, 0, 0, 'fresh', 'lamb', '', '', 'kilo'),
('Lamb Trim', 0, 0, 0, 'fresh', 'lamb', '', '', 'kilo'),
('Lamb Liver', 0, 0, 0, 'fresh', 'lamb', '', '', 'kilo'),
('Lamb Kidney', 0, 0, 0, 'fresh', 'lamb', '', '', 'kilo'),
('Lamb Shank', 0, 0, 0, 'fresh', 'lamb', '', '', 'kilo'),
('Lamb Chops', 0, 0, 0, 'fresh', 'lamb', '', '', 'kilo'),
('Diced Lamb', 0, 0, 0, 'fresh', 'lamb', '', '', 'kilo'),
('Barnsley Chops', 0, 0, 0, 'fresh', 'lamb', '', '', 'kilo'),

('R/Less Loin', 0, 0, 0, 'fresh', 'pork', '', '', 'kilo'),
('B/Less Leg', 0, 0, 0, 'fresh', 'pork', '', '', 'kilo'),
('Pork Collar', 0, 0, 0, 'fresh', 'pork', '', '', 'kilo'),
('Pork Trim', 0, 0, 0, 'fresh', 'pork', '', '', 'kilo'),
('Short Loin', 0, 0, 0, 'fresh', 'pork', '', '', 'kilo'),
('Pork Shoulders B/in', 0, 0, 0, 'fresh', 'pork', '', '', 'kilo'),
('Belly', 0, 0, 0, 'fresh', 'pork', '', '', 'kilo'),
('Gammon Hock', 0, 0, 0, 'fresh', 'pork', '', '', 'kilo'),
('Gammon beef 10oz', 0, 0, 0, 'fresh', 'pork', '', '', 'pack'),
('Gammon beef 8oz', 0, 0, 0, 'fresh', 'pork', '', '', 'pack'),
('Whole Back Smoked', 0, 0, 0, 'fresh', 'pork', '', '', 'kilo'),
('Whole Back Unsmoked', 0, 0, 0, 'fresh', 'pork', '', '', 'kilo'),
('Unsmoked Back Bacon', 0, 0, 0, 'fresh', 'pork', '', '', 'kilo'),
('Unsmoked Streaky', 0, 0, 0, 'fresh', 'pork', '', '', 'kilo'),
('Smoked Streaky', 0, 0, 0, 'fresh', 'pork', '', '', 'kilo'),
('Smoked Gammon', 0, 0, 0, 'fresh', 'pork', '', '', 'kilo'),
('Gammon (bacon?)', 0, 0, 0, 'fresh', 'pork', '', '', 'kilo'),
('Cumberland Sausages 8s', 0, 0, 0, 'fresh', 'pork', '', '', 'kilo'),
('Cumberland Sausages 8s', 0, 0, 0, 'fresh', 'pork', '', '', 'kilo'),
('Gammon Slipper', 0, 0, 0, 'fresh', 'pork', '', '', 'kilo'),

