from ..products import *


def insert_to_database():
    for product in errord_products:
        # Get all values from the product tuple
        name = product[0]
        
        # Convert empty strings to 0 for indices
        cost = 0 if product[1] == "" else product[1]
        stock_count = 0 if product[2] == "" else product[2]
        product_value = 0 if product[3] == "" else product[3]
        
        # Keep the remaining values as is
        stock_category = product[4]
        product_category = product[5]
        sage_code = product[6]
        supplier = product[7]
        sold_as = product[8]
        
        # Insert the product with the potentially modified values
        insert_product(name, cost, stock_count, product_value, stock_category, 
                      product_category, sage_code, supplier, sold_as)

products = [('Topside', 0, 0, 0, 'fresh', 'beef', '', '', 'kilo'),
('Silverside', 0, 0, 0, 'fresh', 'beef', '', '', 'kilo'),
('Brisket', 0, 0, 0, 'fresh', 'beef', '', '', 'kilo'),
('Skirts', 0, 0, 0, 'fresh', 'beef', '', '', 'kilo'),
('Frozen 95vl', 0, 0, 0, 'fresh', 'beef', '', '', 'kilo'),
('Fresh 95vl', 0, 0, 0, 'fresh', 'beef', '', '', 'kilo'),
('85vl', 0, 0, 0, 'fresh', 'beef', '', '', 'kilo'),
('Blades', 0, 0, 0, 'fresh', 'beef', '', '', 'kilo'),
('Chuck', 0, 0, 0, 'fresh', 'beef', '', '', 'kilo'),
('Fore Rib', 0, 0, 0, 'fresh', 'beef', '', '', 'kilo'),
('Pressed Fat', 0, 0, 0, 'fresh', 'beef', '', '', 'kilo'),
('Diced Beef', 0, 0, 0, 'fresh', 'beef', '', '', 'kilo'),
('Rump', 0, 0, 0, 'fresh', 'beef', '', '', 'kilo'),
('Fillet', 0, 0, 0, 'fresh', 'beef', '', '', 'kilo'),
('Fillet Tails', 0, 0, 0, 'fresh', 'beef', '', '', 'kilo'),
('Striploins', 0, 0, 0, 'fresh', 'beef', '', '', 'kilo'),
('Nerve Ends', 0, 0, 0, 'fresh', 'beef', '', '', 'kilo'),
('Rleye-UK', 0, 0, 0, 'fresh', 'beef', '', '', 'kilo'),
('8kg + Striploin', 0, 0, 0, 'fresh', 'beef', '', '', 'kilo'),
('Rump Trim', 0, 0, 0, 'fresh', 'beef', '', '', 'kilo'),
('Fat Trim', 0, 0, 0, 'fresh', 'beef', '', '', 'kilo'),
('Burger Mix', 0, 0, 0, 'fresh', 'beef', '', '', 'kilo'),
('Beef SHin', 0, 0, 0, 'fresh', 'beef', '', '', 'kilo'),

('Mutton Leg', 0, 0, 0, 'fresh', 'lamb', '', '', 'kilo'),
('Lamb Legs', 0, 0, 0, 'fresh', 'lamb', '', '', 'kilo'),
('Lamb Breasts', 0, 0, 0, 'fresh', 'lamb', '', '', 'kilo'),
('Lamb Saddles', 0, 0, 0, 'fresh', 'lamb', '', '', 'kilo'),
('Lamb Trim', 0, 0, 0, 'fresh', 'lamb', '', '', 'kilo'),
('Lamb Liver', 0, 0, 0, 'fresh', 'lamb', '', '', 'kilo'),
('Lamb Kidney', 0, 0, 0, 'fresh', 'lamb', '', '', 'kilo'),
('Lamb Shank', 0, 0, 0, 'fresh', 'lamb', '', '', 'kilo'),
('Lamb Chops', 0, 0, 0, 'fresh', 'lamb', '', '', 'kilo'),
('Diced Lamb', 0, 0, 0, 'fresh', 'lamb', '', '', 'kilo'),
('Barnsley Chops', 0, 0, 0, 'fresh', 'lamb', '', '', 'kilo'),

('R/Less Loin', 0, 0, 0, 'fresh', 'pork', '', '', 'kilo'),
('B/Less Leg', 0, 0, 0, 'fresh', 'pork', '', '', 'kilo'),
('Pork Collar', 0, 0, 0, 'fresh', 'pork', '', '', 'kilo'),
('Pork Trim', 0, 0, 0, 'fresh', 'pork', '', '', 'kilo'),
('Short Loin', 0, 0, 0, 'fresh', 'pork', '', '', 'kilo'),
('Pork Cheek', 0, 0, 0, 'fresh', 'pork', '', '', 'kilo'),
('Pork Fillet', 0, 0, 0, 'fresh', 'pork', '', '', 'kilo'),
('Pork SKin', 0, 0, 0, 'fresh', 'pork', '', '', 'kilo'),
('Short Rib', 0, 0, 0, 'fresh', 'pork', '', '', 'kilo'),
('Pork Shoulders B/in', 0, 0, 0, 'fresh', 'pork', '', '', 'kilo'),
('Belly', 0, 0, 0, 'fresh', 'pork', '', '', 'kilo'),
('Gammon Hock', 0, 0, 0, 'fresh', 'pork', '', '', 'kilo'),
('Gammon beef 10oz', 0, 0, 0, 'fresh', 'pork', '', '', 'pack'),
('Gammon beef 8oz', 0, 0, 0, 'fresh', 'pork', '', '', 'pack'),
('Smoked Gammon', 0, 0, 0, 'fresh', 'pork', '', '', 'kilo'),
('Gammon (bacon?)', 0, 0, 0, 'fresh', 'pork', '', '', 'kilo'),
('Cumberland Sausages 8s', 0, 0, 0, 'fresh', 'pork', '', '', 'kilo'),
('Cumberland Sausages 8s', 0, 0, 0, 'fresh', 'pork', '', '', 'kilo'),
('Gammon Slipper', 0, 0, 0, 'fresh', 'pork', '', '', 'kilo'),

('50/50', 0, 0, 0, 'fresh', 'poultry', '', '', 'kilo'),
('Duck Breasts', 0, 0, 0, 'fresh', 'poultry', '', '', 'kilo'),
('Duck Legs', 0, 0, 0, 'fresh', 'poultry', '', '', 'kilo'),
('Turkey Thigh', 0, 0, 0, 'fresh', 'poultry', '', '', 'kilo'),
('EU Thigh Meat', 0, 0, 0, 'fresh', 'poultry', '', '', 'kilo'),
('1.8', 0, 0, 0, 'fresh', 'poultry', '', '', 'kilo'),
('170-200', 0, 0, 0, 'fresh', 'poultry', '', '', 'kilo'),
('200-300', 0, 0, 0, 'fresh', 'poultry', '', '', 'kilo'),
('Thigh Meat', 0, 0, 0, 'fresh', 'poultry', '', '', 'kilo'),
('UK Breast', 0, 0, 0, 'fresh', 'poultry', '', '', 'kilo'),
('Uk Thigh Meat', 0, 0, 0, 'fresh', 'poultry', '', '', 'kilo'),
('UK Skin on Thigh', 0, 0, 0, 'fresh', 'poultry', '', '', 'kilo'),
('Oyster Thigh', 0, 0, 0, 'fresh', 'poultry', '', '', 'kilo'),
('Diced 50/50', 0, 0, 0, 'fresh', 'poultry', '', '', 'kilo'),
('Turkey', 0, 0, 0, 'fresh', 'poultry', '', '', 'kilo'),
('1.3 Chickens B/Shere', 0, 0, 0, 'fresh', 'poultry', '', '', 'kilo'),

('Sliced Turkey', 0, 0, 0, 'dry', 'poultry', '', '', 'pack'),

('Sliced Beef', 0, 0, 0, 'dry', 'beef', '', '', 'pack'),
('Sliced Corn Beef', 0, 0, 0, 'dry', 'beef', '', '', 'pack'),

('Haggis', 0, 0, 0, 'dry', 'pork', '', '', 'kilo'),
('Gammon', 0, 0, 0, 'dry', 'pork', '', '', 'kilo'),
('Whole Back Smoked', 0, 0, 0, 'dry', 'pork', '', '', 'kilo'),
('Whole Back Unsmoked', 0, 0, 0, 'dry', 'pork', '', '', 'kilo'),
('Unsmoked Back Bacon', 0, 0, 0, 'dry', 'pork', '', '', 'kilo'),
('Unsmoked Streaky', 0, 0, 0, 'dry', 'pork', '', '', 'kilo'),
('Smoked Streaky', 0, 0, 0, 'dry', 'pork', '', '', 'kilo'),
('Fresh Cumberland 8s', 0, 0, 0, 'dry', 'pork', '', '', 'kilo'),
('Fresh Cumberland 6s', 0, 0, 0, 'dry', 'pork', '', '', 'kilo'),

('Diced Venison', 0, 0, 0, 'fresh', 'deer', '', '', 'kilo'),

('3/8 Chips', 0, 0, 0, 'frozen', 'veg', '', '', 'case'),
('Steakhouse Chips', 0, 0, 0, 'frozen', 'veg', '', '', 'case'),
('Crispy Chips', 0, 0, 0, 'frozen', 'veg', '', '', 'case'),
('Hash Browns', 0, 0, 0, 'frozen', 'veg', '', '', 'case'),
('Mash', 0, 0, 0, 'frozen', 'veg', '', '', 'case'),
('Garden Peas', 0, 0, 0, 'frozen', 'veg', '', '', 'case'),
('Sweetcorn', 0, 0, 0, 'frozen', 'veg', '', '', 'case'),
('Green Beans. SL', 0, 0, 0, 'frozen', 'veg', '', '', 'case'),
('Green Beans. Wh', 0, 0, 0, 'frozen', 'veg', '', '', 'case'),
('Broccoli', 0, 0, 0, 'frozen', 'veg', '', '', 'case'),
('Mix Veg', 0, 0, 0, 'frozen', 'veg', '', '', 'case'),
('Button Sprouts', 0, 0, 0, 'frozen', 'veg', '', '', 'case'),
('Cauliflower', 0, 0, 0, 'frozen', 'veg', '', '', 'case'),
('Baby Carrots', 0, 0, 0, 'frozen', 'veg', '', '', 'case'),

('Battered Cod 4-5oz', 0, 0, 0, 'frozen', 'fish', '', '', 'case'),
('Breaded Cod 4-5oz', 0, 0, 0, 'frozen', 'fish', '', '', 'case'),
('Battered Cod 8-10oz', 0, 0, 0, 'frozen', 'fish', '', '', 'case'),
('Fish Fingers', 0, 0, 0, 'frozen', 'fish', '', '', 'case'),
('Fish Cakes', 0, 0, 0, 'frozen', 'fish', '', '', 'case'),
('Wholetail Scampi', 0, 0, 0, 'frozen', 'fish', '', '', 'case'),
('Low Glaze Prawns', 0, 0, 0, 'frozen', 'fish', '', '', 'case'),
('Cod Sless Bless', 0, 0, 0, 'frozen', 'fish', '', '', 'case'),
('Salmon Fillets', 0, 0, 0, 'frozen', 'fish', '', '', 'case'),

('Pork 32s', 0, 0, 0, 'frozen', 'pork', '', '', 'case'),
('Pork 16', 0, 0, 0, 'frozen', 'pork', '', '', 'case'),
('Pork 8', 0, 0, 0, 'frozen', 'pork', '', '', 'case'),
('Pork 4', 0, 0, 0, 'frozen', 'pork', '', '', 'case'),
('Pork SS meat', 0, 0, 0, 'frozen', 'pork', '', '', 'case'),
('Cumberland 16s', 0, 0, 0, 'frozen', 'pork', '', '', 'case'),
('Cumberland 8s', 0, 0, 0, 'frozen', 'pork', '', '', 'case'),
('Best Cumberland 8s', 0, 0, 0, 'frozen', 'pork', '', '', 'case'),
('RSPCA 16s', 0, 0, 0, 'frozen', 'pork', '', '', 'case'),
('RSPCA 8s', 0, 0, 0, 'frozen', 'pork', '', '', 'case'),
('Porkys SausageMeat', 0, 0, 0, 'frozen', 'pork', '', '', 'case'),

('Poultry 8s', 0, 0, 0, 'frozen', 'poultry', '', '', 'case'),
('Poultry 8s HALAL', 0, 0, 0, 'frozen', 'poultry', '', '', 'case'),
('R/Tr 50/50 Chicken', 0, 0, 0, 'frozen', 'poultry', '', '', 'case'),
('Chicken Nuggets', 0, 0, 0, 'frozen', 'poultry', '', '', 'case'),
('D. Cooked Chicken', 0, 0, 0, 'frozen', 'poultry', '', '', 'case'),
('Goujon Brd S/f', 0, 0, 0, 'frozen', 'poultry', '', '', 'case'),
('Goujon Brd H/S', 0, 0, 0, 'frozen', 'poultry', '', '', 'case'),
('Brd Chicken Fillet', 0, 0, 0, 'frozen', 'poultry', '', '', 'case'),

('Beef 8s', 0, 0, 0, 'frozen', 'beef', '', '', 'case'),
('R/Tr Meatballs', 0, 0, 0, 'frozen', 'beef', '', '', 'case'),
('DB Burgers 4oz', 0, 0, 0, 'frozen', 'beef', '', '', 'case'),
('R/Tr Burgers 4oz', 0, 0, 0, 'frozen', 'beef', '', '', 'case'),
('R/Tr Burgers 2oz', 0, 0, 0, 'frozen', 'beef', '', '', 'case'),
('R/Tr Minced Beef', 0, 0, 0, 'frozen', 'beef', '', '', 'case'),
('Porkys Minced Beef', 0, 0, 0, 'frozen', 'beef', '', '', 'case'),

('Grated Mix', 0, 0, 0, 'dry', 'dairy', '', '', 'case'),
('Grated Mature', 0, 0, 0, 'dry', 'dairy', '', '', 'case'),
('Grated Mild', 0, 0, 0, 'dry', 'dairy', '', '', 'case'),
('Grated Mozz', 0, 0, 0, 'dry', 'dairy', '', '', 'case'),
('Grated Mozz/Ch', 0, 0, 0, 'dry', 'dairy', '', '', 'case'),
('Grated Red', 0, 0, 0, 'dry', 'dairy', '', '', 'case'),
('5kg Mature', 0, 0, 0, 'dry', 'dairy', '', '', 'case'),
('5kg MILD', 0, 0, 0, 'dry', 'dairy', '', '', 'case'),

('Baileys Grated mild White Cheese 2kg', 0, 0, 0, 'dry', 'midland', '', '', 'bag'),
('Stilton Blue 1/4 1st Grade 2kg', 0, 0, 0, 'dry', 'midland', '', '', 'kilo'),
('Brie 60% 1kg - Ma Cremiere', 0, 0, 0, 'dry', 'midland', '', '', 'bag'),
('Mature Cheddar 5kg Chase Farm', 0, 0, 0, 'dry', 'midland', '', '', 'kilo'),
('Grated Mature 2kg (AXO15),Chase Farm', 0, 0, 0, 'dry', 'midland', '', '', 'bag'),
('Grana Padano PDO 1kg (', 0, 0, 0, 'dry', 'midland', '', '', 'kilo'),
('Halloumi 250gm', 0, 0, 0, 'dry', 'midland', '', '', 'bag'),
('Black Pudding Stick 1.36kg Oakwell', 0, 0, 0, 'dry', 'midland', '', '', 'bag'),
('Oakvale Frozen Faggots (1x15)', 0, 0, 0, 'dry', 'midland', '', '', 'bag'),
('Danish Salami - Qualitops 1.8kg', 0, 0, 0, 'dry', 'midland', '', '', 'bag'),
('French Style Garlic Stick 1.36kg', 0, 0, 0, 'dry', 'midland', '', '', 'bag'),
('MP Chorizo Stick Extra Mild 1.5kg', 0, 0, 0, 'dry', 'midland', '', '', 'kilo'),
('Pancetta Tesa - San Carlo', 0, 0, 0, 'dry', 'midland', '', '', 'kilo'),
('Tomato Paste 850 ml', 0, 0, 0, 'dry', 'midland', '', '', 'bag'),
('Ardennes Pate 1kg', 0, 0, 0, 'dry', 'midland', '', '', 'bag'),
('Cooked Diced Chicken', 0, 0, 0, 'dry', 'midland', '', '', 'bag'),
('Grand Mere Brussels Pate Log 1kg', 0, 0, 0, 'dry', 'midland', '', '', 'bag'),
('Tuna Chunks/Brine (Parkdale),1.7kg', 0, 0, 0, 'dry', 'midland', '', '', 'bag'),
('Mission Plane Tortilla (10"),5x18x4', 0, 0, 0, 'dry', 'midland', '', '', 'case'),
('Oakvale Scotch Eggs', 0, 0, 0, 'dry', 'midland', '', '', 'bag'),
('King Size Sausage Rolls', 0, 0, 0, 'dry', 'midland', '', '', 'case'),
('Chicken & Mushroom Pie', 0, 0, 0, 'dry', 'midland', '', '', 'case'),
('Large Pastry', 0, 0, 0, 'dry', 'midland', '', '', 'case'),
('Gala Pork Pie with Egg', 0, 0, 0, 'dry', 'midland', '', '', 'case'),
('TCM Small Pork Pies x12', 0, 0, 0, 'dry', 'midland', '', '', 'case'),
('Saveloys 4.08kg (36),- Tasty Bake', 0, 0, 0, 'dry', 'midland', '', '', 'case'),
('St Nicholas Baked Beans 6 x 2.65kg', 0, 0, 0, 'dry', 'midland', '', '', 'case'),
('Bella Napoli Plum Tomatoes 6x2.5kg', 0, 0, 0, 'dry', 'midland', '', '', 'case'),
('Bella Napoli Chopped Tomatoes 6x2.50kg', 0, 0, 0, 'dry', 'midland', '', '', 'case'),
('T/S (7002),White Baguette 30 x 135gm', 0, 0, 0, 'dry', 'midland', '', '', 'case'),
('P/B (7009),Malted Wheat Baguette 30x135', 0, 0, 0, 'dry', 'midland', '', '', 'case'),
('Chase Farm Sliced 100% Beef ', 0, 0, 0, 'dry', 'midland', '', '', 'bag'),
('Chase Farm Sliced Bentley Roast Turkey', 0, 0, 0, 'dry', 'midland', '', '', 'bag'),
('Chase Farm Sliced 92% Chicken', 0, 0, 0, 'dry', 'midland', '', '', 'bag'),
('Sliced Pancetta Affumicata', 0, 0, 0, 'dry', 'midland', '', '', 'bag'),
('Sliced Proscuitto 80g', 0, 0, 0, 'dry', 'midland', '', '', 'bag'),
('Sliced Proscuitto 500g', 0, 0, 0, 'dry', 'midland', '', '', 'bag'),
('CHASE FARM Sliced Corn Beef 500g', 0, 0, 0, 'dry', 'midland', '', '', 'bag'),
('CHASE FARM Sliced Gamman Ham 500g', 0, 0, 0, 'dry', 'midland', '', '', 'bag'),
('Sliced Chorizo Mild 250gm', 0, 0, 0, 'dry', 'midland', '', '', 'bag'),
('Mini BBQ Chorizo', 0, 0, 0, 'dry', 'midland', '', '', 'bag'),
('5kg Mild', 0, 0, 0, 'dry', 'midland', '', '', 'case'),
('Hash Browns', 0, 0, 0, 'dry', 'midland', '', '', 'case'),
('Liver sausage 1kg', 0, 0, 0, 'dry', 'midland', '', '', 'bag'),
('2.5kgs Mixed Veg', 0, 0, 0, 'dry', 'midland', '', '', 'bag'),
('2.5kgs Garden Peas', 0, 0, 0, 'dry', 'midland', '', '', 'bag'),
('Tins of Sweetcorn', 0, 0, 0, 'dry', 'midland', '', '', 'bag')
]





products_2 = [("kgs x Smoked Gammon Joints B&R", "", "", "", "fresh", "", "BAC1", "", "", ""), 
	("kgs x Gammon B&R", "", "", "", "fresh", "", "BAC2", "", "", ""), 
	("kgs x Whole Gammon Converter", "", "", "", "fresh", "", "BAC21", "", "", ""), 
	("pk 4 x 4oz Gammon Steaks", "", "", "", "fresh", "", "BAC5", "", "", ""), 
	("pk 2 x 6oz Gammon Steaks", "", "", "", "fresh", "", "BAC6", "", "", ""), 
	("pk 2 x 8oz Gammon Steaks", "", "", "", "fresh", "", "BAC7", "", "", ""), 
	("pk 5 x 6oz Half Moon Gammon Steaks", "", "", "", "fresh", "", "BAC71", "", "", ""), 
	("ea x 8oz Horseshoe Gammon Steaks", "", "", "", "fresh", "", "BAC711", "", "", ""), 
	("pk x 2.27kg Rless Streaky Bacon", "", "", "", "fresh", "", "BAC8", "", "", ""), 
	("pkt x 1lb Streaky Bacon", "", "", "", "fresh", "", "BAC80", "", "", ""), 
	("pk x 2.27kg Smoked Streaky Bacon", "", "", "", "fresh", "", "BAC81", "", "", ""), 
	("ea x 1lb Smoked Streaky Bacon", "", "", "", "fresh", "", "BAC811", "", "", ""), 
	("ea x 10oz Horseshoe Gammon Steaks", "", "", "", "fresh", "", "BAC92", "", "", ""), 
	("ea x 12oz Horseshoe Gammon Steaks", "", "", "", "fresh", "", "BAC93", "", "", ""), 
	("kgs x Green Horseshoe Gammon B&R", "", "", "", "fresh", "", "BAC94", "", "", ""), 
	("kgs x Diced Gammon", "", "", "", "fresh", "", "BAC95", "", "", ""), 
	("kgs x Whole Green Back Bacon", "", "", "", "fresh", "", "BAC97", "", "", ""), 
	("kgs x Bacon Hocks", "", "", "", "fresh", "", "BAC98", "", "", ""), 
	("kgs x Smoked Bacon Hocks", "", "", "", "fresh", "", "BAC981", "", "", ""), 
	("kgs x Hand Diced Top Rump 1", "", "", "", "fresh", "", "BE1", "", ""), 
	("kgs x Beef Short Ribs", "", "", "", "fresh", "", "BE10", "", ""), 
	("kgs x Beef Skirt", "", "", "", "fresh", "", "BE12", "", ""), 
	("kgs x Hand Diced Beef Steak", "", "", "", "fresh", "", "BE2", "", ""), 
	("kgs x Whole Chuck Steak", "", "", "", "fresh", "", "BE21", "", ""), 
	("kgs x HALAL Diced Beef 95%", "", "", "", "fresh", "", "BE3", "", ""), 
	("kgs x 80vl Minced Beef - COURSE", "", "", "", "fresh", "", "BE31", "", ""), 
	("kgs x 95% Minced Beef", "", "", "", "fresh", "", "BE4", "", ""), 
	("kgs x  HALAL Minced Beef 95% - FROZEN", "", "", "", "fresh", "", "BE41", "", ""), 
	("x 1kgs Organic Minced Beef 85% - FROZEN", "", "", "", "fresh", "", "BE411", "", ""), 
	("kgs x  UK Minced Beef 95% - FROZEN", "", "", "", "fresh", "", "BE4111", "", ""), 
	("kgs x 98% Ex Lean Mince Beef", "", "", "", "fresh", "", "BE41111", "", ""), 
	("kgs x Mince Chuck / Minced Rump 80vl S/W", "", "", "", "fresh", "", "BE411111", "", ""), 
	("kgs x Corner Cut Topside", "", "", "", "fresh", "", "BE5", "", ""), 
	("kgs x Best UK Prime Topside", "", "", "", "fresh", "", "BE6", "", ""), 
	("kgs x Minced Brisket / Chuck / Tallow (40/40/20)", "", "", "", "fresh", "", "BE61", "", ""), 
	("kgs x UK Silverside B&R", "", "", "", "fresh", "", "BE7", "", ""), 
	("kgs x Flat Brisket Boneless", "", "", "", "fresh", "", "BE9", "", ""), 
	("kgs x Carvery Ribs Beef", "", "", "", "fresh", "", "BE92", "", ""), 
	("kgs x Rib of Beef", "", "", "", "fresh", "", "BE93", "", ""), 
	("kgs Brisket Boned & Rolled", "", "", "", "fresh", "", "BE931", "", ""), 
	("ea x Whole Full Rib Tomahawk Steak", "", "", "", "fresh", "", "BE94", "", ""), 
	("kgs x Rump Strips/Goujons", "", "", "", "fresh", "", "BE941", "", ""), 
	("kgs x Fillet Tails", "", "", "", "fresh", "", "BE9411", "", ""), 
	("kgs x Whole Trimmed Blades S/W", "", "", "", "fresh", "", "BE95", "", ""), 
	("kgs x Whole Blade of Beef", "", "", "", "fresh", "", "BE951", "", ""), 
	("kgs x Top Rump/Thick Flank", "", "", "", "fresh", "", "BE96", "", ""), 
	("kgs x Stir Fry Beef", "", "", "", "fresh", "", "BE97", "", ""), 
	("kgs x 8kg+ Prime Striploin of Beef", "", "", "", "fresh", "", "BE970", "", ""), 
	("ea x 5oz Minute Steaks", "", "", "", "fresh", "", "BE971", "", ""), 
	("kgs x 6kgs+ Prime Striploin", "", "", "", "fresh", "", "BE98", "", ""), 
	("ea x 10oz Sirlon Steaks", "", "", "", "fresh", "", "BE980", "", ""), 
	("ea x 8oz UK Sirloin Steaks", "", "", "", "fresh", "", "BE981", "", ""), 
	("ea x 10oz Imp Sirloin Steaks", "", "", "", "fresh", "", "BE9811", "", ""), 
	("ea x 6oz Sirloin Steaks", "", "", "", "fresh", "", "BE98111", "", ""), 
	("kgs x Sirloin Steaks", "", "", "", "fresh", "", "BE9811111", "", ""), 
	("ea x 9oz Sirloin Steak", "", "", "", "fresh", "", "BE982", "", ""), 
	("ea x 9-10oz Dry-Aged Ribeye Steak", "", "", "", "fresh", "", "BE984", "", ""), 
	("ea x 600g Chateaubriand", "", "", "", "fresh", "", "BE989", "", ""), 
	("kgs x Whole Rump of Beef", "", "", "", "fresh", "", "BE99", "", ""), 
	("ea x 8oz Flat Iron Steaks", "", "", "", "fresh", "", "BE990", "", ""), 
	("ea x 6oz Flat Irion Steaks", "", "", "", "fresh", "", "BE9901", "", ""), 
	("ea x 10oz Rump Steaks", "", "", "", "fresh", "", "BE991", "", ""), 
	("ea x 8oz Rump Steaks", "", "", "", "fresh", "", "BE9911", "", ""), 
	("ea x 6oz Rump Steaks", "", "", "", "fresh", "", "BE991111", "", ""), 
	("ea x 4-5oz Rump Steaks", "", "", "", "fresh", "", "BE9911111", "", ""), 
	("ea x 7oz Rump Steaks", "", "", "", "fresh", "", "BE992", "", ""), 
	("kgs x Rump Steaks", "", "", "", "fresh", "", "BE9921", "", ""), 
	("ea x 12oz Rump Steak", "", "", "", "fresh", "", "BE99211", "", ""), 
	("ea x 6oz Fillet Steaks", "", "", "", "fresh", "", "BE993", "", ""), 
	("ea x 7oz Fillet Steaks", "", "", "", "fresh", "", "BE9930", "", ""), 
	("ea x 8oz Fillet Steaks", "", "", "", "fresh", "", "BE9931", "", ""), 
	("ea x 10oz Fillet Steaks", "", "", "", "fresh", "", "BE99311", "", ""), 
	("ea x 12oz Fillet Steaks", "", "", "", "fresh", "", "BE993111", "", ""), 
	("ea x 8oz Fillet Steaks - Middle Cut", "", "", "", "fresh", "", "BE9931111", "", ""), 
	("ea x 16-18oz T-Bone Steaks", "", "", "", "fresh", "", "BE9932", "", ""), 
	("ea x 5oz Fillet Medallion Steaks", "", "", "", "fresh", "", "BE9933", "", ""), 
	("kgs x Braising Steaks", "", "", "", "fresh", "", "BE994", "", ""), 
	("kgs x Red Tractor Sliced Braising Steaks", "", "", "", "fresh", "", "BE9941", "", ""), 
	("kgs x Diced Steak & Kidney", "", "", "", "fresh", "", "BE997", "", ""), 
	("kgs x Whole Fillets", "", "", "", "fresh", "", "BE9971", "", ""), 
	("kgs x Whole Fillets Beef 2kg+ Extra Mature / Trimmed S/W", "", "", "", "fresh", "", "BE998", "", ""), 
	("kgs x Whole Fillets Beef - Trimmed", "", "", "", "fresh", "", "BE9981", "", ""), 
	("kgs x Whole Rib Eyes", "", "", "", "fresh", "", "BE999", "", ""), 
	("ea x 8oz Ribeye Steaks", "", "", "", "fresh", "", "BE9991", "", ""), 
	("ea x 10oz Ribeye Steaks", "", "", "", "fresh", "", "BE99911", "", ""), 
	("ea x 12oz Ribeye Steaks", "", "", "", "fresh", "", "BE999111", "", ""), 
	("ea x 10oz Signature Angus Ribeye Steak", "", "", "", "fresh", "", "BE9991111", "", ""), 
	("ea x 12oz Signature Angus Ribeye Steak", "", "", "", "fresh", "", "BE9992", "", ""), 
	("ea x 7oz Rib Eye Steaks", "", "", "", "fresh", "", "BE99921", "", ""), 
	("kgs x Fresh Boned Striploins", "", "", "", "fresh", "", "BE9993", "", ""), 
	("Cote De Beouf", "", "", "", "fresh", "", "BE99993", "", ""), 
	("kgs x Fresh Calves Kidneys - suet on", "", "", "", "fresh", "", "BEEF0", "", ""), 
	("kgs x Caul Fat/Creponet", "", "", "", "fresh", "", "BEEF01", "", ""), 
	("kgs x Veal Fillets", "", "", "", "fresh", "", "BEEF1111", "", ""), 
	("ea x 300g Veal Chops", "", "", "", "fresh", "", "BEEF11111", "", ""), 
	("kgs x Veal Bones", "", "", "", "fresh", "", "BEEF2", "", ""), 
	("kgs x Osso Bucco", "", "", "", "fresh", "", "BEEF21", "", ""), 
	("kgs x Calves Feet - Split", "", "", "", "fresh", "", "BEEF211", "", ""), 
	("kgs x Fresh Calf Liver", "", "", "", "fresh", "", "BEEF3", "", ""), 
	("kgs x Veal Silverside", "", "", "", "fresh", "", "BEEF4", "", ""), 
	("kgs x Veal Bone Pucks", "", "", "", "fresh", "", "BEEF5", "", ""), 
	("kgs x Veal Escallopes", "", "", "", "fresh", "", "BEEF6", "", ""), 
	("kgs x Veal Topside", "", "", "", "fresh", "", "BEEF7", "", ""), 
	("kgs x UK Veal Rump", "", "", "", "fresh", "", "BEEF911", "", ""), 
	("kgs x Loin of Veal", "", "", "", "fresh", "", "BEEFO", "", ""), 
	("kgs x 95vl Minced Beef -  HALAL", "", "", "", "fresh", "", "BEH4", "", ""), 
	("kgs x Duck Legs", "", "", "", "fresh", "", "CH8", "", ""), 
	("kgs x 300-350g Frozen Polish Duck Legs", "", "", "", "fresh", "", "CH81", "", ""), 
	("kgs x Corn Fed Fresh Chicken", "", "", "", "fresh", "", "CHR", "", ""), 
	("kgs x Smoked Chicken Breasts", "", "", "", "fresh", "", "CHR0", "", ""), 
	("ea x Uncooked Chicken Legs", "", "", "", "fresh", "", "CHR1", "", ""), 
	("ea x Extra Large Chicken Legs - Cut from 1.8s", "", "", "", "fresh", "", "CHR11", "", ""), 
	("kgs x Whole Fresh Chicken", "", "", "", "fresh", "", "CHR2", "", ""), 
	("ea x Skin On Chicken Breast Fillet", "", "", "", "fresh", "", "CHR21", "", ""), 
	("kgs x Whole Smoked Chicken", "", "", "", "fresh", "", "CHR22", "", ""), 
	("kgs x 1.8kgs Whole Chicken", "", "", "", "fresh", "", "CHR3", "", ""), 
	("ea x 3-4oz Chicken Escalopes", "", "", "", "fresh", "", "CHR30", "", ""), 
	("ea. 6/7oz Chicken Breast Fillets - Butterfly", "", "", "", "fresh", "", "CHR301", "", ""), 
	("ea x 6-7oz Chicken Breast Fillets", "", "", "", "fresh", "", "CHR31", "", ""), 
	("ea x 8-9oz Chicken Breast Fillets", "", "", "", "fresh", "", "CHR311", "", ""), 
	("ea x Chicken Breast Quarters", "", "", "", "fresh", "", "CHR3111", "", ""), 
	("ea x Corn Fed Chicken Supremes", "", "", "", "fresh", "", "CHR4", "", ""), 
	("c/s x 1.4 - 1.7kg Free Range Fresh Chicken", "", "", "", "fresh", "", "CHR401", "", ""), 
	("ea x Skin on Supremes", "", "", "", "fresh", "", "CHR41", "", ""), 
	("ea x Skin on Supreme - Fr/Tr", "", "", "", "fresh", "", "CHR410", "", ""), 
	("ea x Extra Large Chicken Supremes - Cut From 1.8s", "", "", "", "fresh", "", "CHR411", "", ""), 
	("ea. Red Tractor Chicken Supremes", "", "", "", "fresh", "", "CHR4111", "", ""), 
	("kgs x Fresh Chicken Quarters", "", "", "", "fresh", "", "CHR5", "", ""), 
	("ea x Fresh Chicken Halves - cut from 1.2kgs", "", "", "", "fresh", "", "CHR51", "", ""), 
	("ea x Spatchcock chicken - Cut into halves", "", "", "", "fresh", "", "CHR52", "", ""), 
	("ea x 16-18oz Poussin", "", "", "", "fresh", "", "CHR6", "", ""), 
	("c/s 24 ptns Fresh Chicken Quarters (6 birds),Boxed", "", "", "", "fresh", "", "CHR7", "", ""), 
	("kgs x Chicken Drumsticks", "", "", "", "fresh", "", "CHR9", "", ""), 
	("kgs x Gressingham B'less Duck Breasts", "", "", "", "fresh", "", "CHR91", "", ""), 
	("kgs x 200-220g Frozen Polish Duck Breast", "", "", "", "fresh", "", "CHR911", "", ""), 
	("kgs x Smoked Duck Breasts", "", "", "", "fresh", "", "CHR9111", "", ""), 
	("kgs x Chicken Oyster Thighs", "", "", "", "fresh", "", "CHR92", "", ""), 
	("x B'less Chicken Thighs", "", "", "", "fresh", "", "CHR920", "", ""), 
	("kgs x B'less Skin-on Chicken Thighs", "", "", "", "fresh", "", "CHR9201", "", ""), 
	("kgs x Diced Chicken Thigh Meat", "", "", "", "fresh", "", "CHR921", "", ""), 
	("kgs x Whole Chicken Thigh Meat", "", "", "", "fresh", "", "CHR922", "", ""), 
	("kgs x B'less Chicken Breasts", "", "", "", "fresh", "", "CHR93", "", ""), 
	("kgs x Diced Chicken Breast Meat", "", "", "", "fresh", "", "CHR94", "", ""), 
	("kgs x Diced Chicken Breast & Dark Meat", "", "", "", "fresh", "", "CHR941", "", ""), 
	("kgs x  Diced Chicken Mix Meat (50/50),-  FROZEN", "", "", "", "fresh", "", "CHR9411", "", ""), 
	("kgs x 3-Bone Chicken Wings", "", "", "", "fresh", "", "CHR95", "", ""), 
	("kgs x Chicken Breast Strips", "", "", "", "fresh", "", "CHR951", "", ""), 
	("kgs x Jumbo Chicken Wings", "", "", "", "fresh", "", "CHR952", "", ""), 
	("kgs x 2 Bone Chicken Wings - FRESH", "", "", "", "fresh", "", "CHR953", "", ""), 
	("kgs x Chicken Bones", "", "", "", "fresh", "", "CHR96", "", ""), 
	("kgs x Chicken Boned & Rolled", "", "", "", "fresh", "", "CHR97", "", ""), 
	("kgs x Chicken Skin", "", "", "", "fresh", "", "CHR98", "", ""), 
	("kgs x Whole Frozen Ducks", "", "", "", "fresh", "", "CHR997", "", ""), 
	("kgs x Whole Fresh Gressingham Ducks", "", "", "", "fresh", "", "CHR998", "", ""), 
	("kgs x Stir Fry Chicken", "", "", "", "fresh", "", "CHR999", "", ""), 
	("kgs x Chicken Crowns", "", "", "", "fresh", "", "CHR9999", "", ""), 
	("pk x 2.5kgs Diced Mixed Game", "", "", "", "fresh", "", "GA1", "", ""), 
	("pk 2 x 6oz Venison Steaks", "", "", "", "fresh", "", "GA2", "", ""), 
	("kgs x Goose Legs", "", "", "", "fresh", "", "GA3", "", ""), 
	("kgs x Whole Guinea Fowl", "", "", "", "fresh", "", "GA4", "", ""), 
	("ea x Guinea Fowl Supremes", "", "", "", "fresh", "", "GA41", "", ""), 
	("kgs x Diced Venison", "", "", "", "fresh", "", "GA5", "", ""), 
	("kgs x Wild Boar Saddles", "", "", "", "fresh", "", "GA51", "", ""), 
	("pk 2 x Wild Boar Steaks", "", "", "", "fresh", "", "GA6", "", ""), 
	("pk 2 x 175g Ostrich Steaks", "", "", "", "fresh", "", "GA71", "", ""), 
	("ea x Whole Pheasant", "", "", "", "fresh", "", "GA8", "", ""), 
	("ea x Whole Partridge", "", "", "", "fresh", "", "GA81", "", ""), 
	("pk 10 x 4-5oz Pheasant Breasts", "", "", "", "fresh", "", "GA811", "", ""), 
	("kgs x Saddle of Venison", "", "", "", "fresh", "", "GA9", "", ""), 
	("kgs x 2.5kgs Diced Venison FROZEN", "", "", "", "fresh", "", "GA91", "", ""), 
	("kgs x Rabbit Saddles", "", "", "", "fresh", "", "GA92", "", ""), 
	("kgs x Rabbit Legs (pack of 6)", "", "", "", "fresh", "", "GA93", "", ""), 
	("kgs x Saddles of Hare - on the bone", "", "", "", "fresh", "", "GA931", "", ""), 
	("ea x Whole Wood Pigeon", "", "", "", "fresh", "", "GA94", "", ""), 
	("kgs 2 x Crocodile Steaks", "", "", "", "fresh", "", "GA95", "", ""), 
	("kgs x Diced Wild Boar", "", "", "", "fresh", "", "GA96", "", ""), 
	("pk 2 x Kangaroo Steaks", "", "", "", "fresh", "", "GAT1", "", ""), 
	("kgs x Venison Striploin", "", "", "", "fresh", "", "GAT100", "", ""), 
	("kgs x 8oz Kangaroo Rump Steaks - in 2s", "", "", "", "fresh", "", "GAT12", "", ""), 
	("kgs x Whole Rabbits", "", "", "", "fresh", "", "GAT13", "", ""), 
	("pk x Zebra Steaks", "", "", "", "fresh", "", "GAT14", "", ""), 
	("pk 2 x Ostrich Steaks in Marakesh Sauce", "", "", "", "fresh", "", "GAT15", "", ""), 
	("pk 12 x Quail Eggs", "", "", "", "fresh", "", "GAT2", "", ""), 
	("ea x Whole Quail - bone in", "", "", "", "fresh", "", "GAT3", "", ""), 
	("pk 10 x Wood Pigeon Breasts", "", "", "", "fresh", "", "GAT5", "", ""), 
	("kgs x BBQ Chicken Strips", "", "", "", "fresh", "", "GLZB1", "", ""), 
	("kgs x BBQ S'on B'less Chicken Thighs", "", "", "", "fresh", "", "GLZB2", "", ""), 
	("kgs x BBQ Pork Belly Slices", "", "", "", "fresh", "", "GLZB3", "", ""), 
	("kgs x Cajun Glazed Chicken Stir Fry", "", "", "", "fresh", "", "GLZCJ1", "", ""), 
	("5 x 3/4oz Minted Lamb Rumps", "", "", "", "fresh", "", "GLZM", "", ""), 
	("KG x Hot and spicey Chicken Wings", "", "", "", "fresh", "", "GLZM1", "", ""), 
	("kgs x Sweet Chilli Pork Belly Slices", "", "", "", "fresh", "", "GLZSC", "", ""), 
	("kgs x Sweet Chilli S'on B'less Chicken Thighs", "", "", "", "fresh", "", "GLZSC1", "", ""), 
	("kgs x Sweet Chilli Chicken Strips", "", "", "", "fresh", "", "GLZSC2", "", ""), 
	("kgs x Gammon Joints B&R R/Tr", "", "", "", "fresh", "", "IDCBAC21", "", ""), 
	("kgs x Gammon Joints B&R R/Tr - FROZEN", "", "", "", "fresh", "", "IDCBAC211", "", ""), 
	("pkt (2.27kgs),R'less Back Bacon", "", "", "", "fresh", "", "IDCBAC3", "", ""), 
	("c/s (4x2.27kgs),R'less Back Bacon", "", "", "", "fresh", "", "IDCBAC31", "", ""), 
	("kgs x UK Diced Beef", "", "", "", "fresh", "", "IDCBE2", "", ""), 
	("kgs x UK Diced Beef - FROZEN", "", "", "", "fresh", "", "IDCBE21", "", ""), 
	("kgs x UK Mince Beef", "", "", "", "fresh", "", "IDCBE4", "", ""), 
	("kgs x  UK Mince Beef - FROZEN", "", "", "", "fresh", "", "IDCBE41", "", ""), 
	("kgs x Halal Mince Beef", "", "", "", "fresh", "", "IDCBE411", "", ""), 
	("kgs x Halal Mince Beef- FROZEN", "", "", "", "fresh", "", "IDCBE4111", "", ""), 
	("kgs Whole Brisket", "", "", "", "fresh", "", "IDCBE5", "", ""), 
	("kgs x UK Beef  Topside Joints", "", "", "", "fresh", "", "IDCBE7", "", ""), 
	("kgs x UK Beef Topside Joints -FROZEN", "", "", "", "fresh", "", "IDCBE71", "", ""), 
	("kgs UK Beef Stir-Fry", "", "", "", "fresh", "", "IDCBE997", "", ""), 
	("kgs x UK Beef Stir-Fry -FROZEN", "", "", "", "fresh", "", "IDCBE9971", "", ""), 
	("pkt (UK 960g),Breaded Chicken Steaks", "", "", "", "fresh", "", "IDCCC01", "", ""), 
	("x 1kg pkt UK Breaded Chicken Goujons - Southern", "", "", "", "fresh", "", "IDCCC02", "", ""), 
	("x 1kg pkt UK Breaded Chicken Goujons - Hot & Spicy", "", "", "", "fresh", "", "IDCCC03", "", ""), 
	("case 5kgs Tempura Battered Chicken Steaks (85g)", "", "", "", "fresh", "", "IDCCH1", "", ""), 
	("ea x 6/7oz Chicken Fillets", "", "", "", "fresh", "", "IDCCH31", "", ""), 
	("x1kgs Chicken Goujons - Plain FROZEN", "", "", "", "fresh", "", "IDCCH5", "", ""), 
	("pkt 1kgs Chicken Goujons-Glazed -Southern coated-FROZEN", "", "", "", "fresh", "", "IDCCH51", "", ""), 
	("kgs x Chicken Drumsticks - FROZEN", "", "", "", "fresh", "", "IDCCH9", "", ""), 
	("kgs x Chicken Oyster Thighs - FROZEN", "", "", "", "fresh", "", "IDCCH91", "", ""), 
	("kgs Chicken Thighs (bone-less)", "", "", "", "fresh", "", "IDCCH92", "", ""), 
	("kgs  Chicken Thighs (bone-less),FROZEN", "", "", "", "fresh", "", "IDCCH921", "", ""), 
	("kgs Whole Boneless Chicken Thigh Meat", "", "", "", "fresh", "", "IDCCH931", "", ""), 
	("kgs Diced Chicken Mix (50/50)", "", "", "", "fresh", "", "IDCCH94", "", ""), 
	("kgs x Diced Chicken Mix (50/50) - FROZEN", "", "", "", "fresh", "", "IDCCH941", "", ""), 
	("kgs x Mince Chicken Mix (50/50) - FROZEN", "", "", "", "fresh", "", "IDCCH9411", "", ""), 
	("kgs Diced Chicken Breast", "", "", "", "fresh", "", "IDCCH95", "", ""), 
	("kgs x Diced Chicken Breast - FROZEN", "", "", "", "fresh", "", "IDCCH951", "", ""), 
	("Kgs Chicken Breast stir-fry", "", "", "", "fresh", "", "IDCCH96", "", ""), 
	("kgs x Chicken Breast stir-fry - FROZEN", "", "", "", "fresh", "", "IDCCH961", "", ""), 
	("kgs Chicken Wings FROZEN", "", "", "", "fresh", "", "IDCCH97", "", ""), 
	("ea. Chicken Legs - oyster cut", "", "", "", "fresh", "", "IDCCH98", "", ""), 
	("kgs Chicken Breast Inner Fillets", "", "", "", "fresh", "", "IDCCH981", "", ""), 
	("pk x 500g UK Sliced Gammon Ham", "", "", "", "fresh", "", "IDCCME9811", "", ""), 
	("pk x 500g UK Sliced Roast Beef", "", "", "", "fresh", "", "IDCCME99", "", ""), 
	("pk 500g x Sliced Roast Turkey", "", "", "", "fresh", "", "IDCCME991", "", ""), 
	("pk x 500g UK Sliced Corn Beef", "", "", "", "fresh", "", "IDCCME992", "", ""), 
	("kgs x 5kg Mature Cheddar", "", "", "", "fresh", "", "IDCDAR3", "", ""), 
	("kgs x 5kg Mild Cheddar", "", "", "", "fresh", "", "IDCDAR4", "", ""), 
	("c/s 5 x 2kg Grated Mild Cheese", "", "", "", "fresh", "", "IDCDAR6", "", ""), 
	("c/s 5 x 2kg Grated Mature Cheese", "", "", "", "fresh", "", "IDCDAR61", "", ""), 
	("c/s 5 x 2kgs Grated Mozzarella & Cheddar Mix", "", "", "", "fresh", "", "IDCDAR611", "", ""), 
	("*EMPTY NAME REPLACE*", "", "", "", "fresh", "", "IDCFF6", "", ""), 
	("c/s 24 x 4-5oz Breaded Cod Fillets", "", "", "", "fresh", "", "IDCFF8", "", ""), 
	("c/s 24 x 4-5oz Battered Cod Fillets", "", "", "", "fresh", "", "IDCFF92", "", ""), 
	("pk x 2kgs Low Glaze Prawns", "", "", "", "fresh", "", "IDCFF992", "", ""), 
	("c/s 24x4oz Hmade Beef Burgers - FROZEN", "", "", "", "fresh", "", "IDCJL1", "", ""), 
	("c/s 48x2oz Hmade Beef Burgers - FROZEN", "", "", "", "fresh", "", "IDCJL2", "", ""), 
	("kgs x Minced Lamb", "", "", "", "fresh", "", "IDCLA1", "", ""), 
	("kgs x UK Pork Joints B'less - LEG", "", "", "", "fresh", "", "IDCPO2", "", ""), 
	("kgs x UK Pork Joints B'less - LEG - FROZEN", "", "", "", "fresh", "", "IDCPO21", "", ""), 
	("kgs UK Pork Joints B'less - Loin", "", "", "", "fresh", "", "IDCPO4", "", ""), 
	("kgs UK Pork Joints B'less - Loin - FROZEN", "", "", "", "fresh", "", "IDCPO41", "", ""), 
	("kgs UK Pork Collar", "", "", "", "fresh", "", "IDCPO5", "", ""), 
	("kgs UK Pork Collar - FROZEN", "", "", "", "fresh", "", "IDCPO51", "", ""), 
	("kgs UK Diced Pork", "", "", "", "fresh", "", "IDCPO71", "", ""), 
	("kgs x UK Diced Pork - FROZEN", "", "", "", "fresh", "", "IDCPO711", "", ""), 
	("kgs UK Stir-fry Pork", "", "", "", "fresh", "", "IDCPO92", "", ""), 
	("kgs x UK Stir-fry Pork - FROZEN", "", "", "", "fresh", "", "IDCPO921", "", ""), 
	("kgs UK Pork Spare Ribs", "", "", "", "fresh", "", "IDCPO95", "", ""), 
	("kgs UK Minced Pork", "", "", "", "fresh", "", "IDCPO96", "", ""), 
	("kgs x UK Minced Pork - FROZEN", "", "", "", "fresh", "", "IDCPO961", "", ""),	("kgs Pork Baby Back Ribs", "", "", "", "fresh", "", "IDCPO971", "", ""), 
	("kgs Pork Baby Back Ribs - portioned", "", "", "", "fresh", "", "IDCPO9711", "", ""), 
	("c/s Poultry Sausages 8'S", "", "", "", "fresh", "", "IDCSS222", "", ""), 
	("c/s Pork 4s", "", "", "", "fresh", "", "IDCSS411", "", ""), 
	("c/s RSPCA Approval Pork 8s", "", "", "", "fresh", "", "IDCSS4111", "", ""), 
	("c/s RSPCA Approval Pork 16s", "", "", "", "fresh", "", "IDCSS41111", "", ""), 
	("c/s Pork 16's - GREEN LABEL", "", "", "", "fresh", "", "IDCSS51", "", ""), 
	("c/s Beef Sausages", "", "", "", "fresh", "", "IDCSS71", "", ""), 
	("x 1lb (IDC),HOMEMADE CUMBERLAND Sausage Meat - FROZEN", "", "", "", "fresh", "", "IDCSS933", "", ""), 
	("Sl. Chorizo 250g Pack", "", "", "", "fresh", "", "IDCSS9941", "", ""), 
	("kgs x Diced Turkey", "", "", "", "fresh", "", "IDCTK4", "", ""), 
	("kgs  x  Diced Turkey - FROZEN", "", "", "", "fresh", "", "IDCTK41", "", ""), 
	("kgs x Turkey Breast Roll", "", "", "", "fresh", "", "IDCTK5", "", ""), 
	("kgs x Turkey Breast Roll - FROZEN", "", "", "", "fresh", "", "IDCTK51", "", ""), 
	("kgs Turkey Breast Stir-Fry", "", "", "", "fresh", "", "IDCTKY3", "", ""), 
	("kgs x Minced Turkey - FROZEN", "", "", "", "fresh", "", "IDCTKY31", "", ""), 
	("c/s 4 x 2.5kgs Steak House Chips", "", "", "", "fresh", "", "IDCVEG111", "", ""), 
	("2.5kgs pk Garden Peas", "", "", "", "fresh", "", "IDCVEG711", "", ""), 
	("2.5kgs pk Sliced Green Beans", "", "", "", "fresh", "", "IDCVEG81", "", ""), 
	("2.5kgs pk Whole Green Beans", "", "", "", "fresh", "", "IDCVEG811", "", ""), 
	("2.5kgs pk Cauliflower", "", "", "", "fresh", "", "IDCVEG931", "", ""), 
	("2.5kgs pk Sweetcorn", "", "", "", "fresh", "", "IDCVEG9811", "", ""), 
	("2.5kgs pk Diced peppers", "", "", "", "fresh", "", "IDCVEG9999", "", ""), 
	("c/s 48x4oz 100% Beefburgers", "", "", "", "fresh", "", "JLB1", "", ""), 
	("ea x 6oz Rump Chuck & Tallow Burgers", "", "", "", "fresh", "", "JLB10", "", ""), 
	("ea x 3oz Hmade Beef Burgers - GF", "", "", "", "fresh", "", "JLB11", "", ""), 
	("c/s 48x2oz Beef Burgers- Halal", "", "", "", "fresh", "", "JLB1H", "", ""), 
	("ea x 6oz Lamb & Mint Burger", "", "", "", "fresh", "", "JLB2", "", ""), 
	("ea x 98vl 8oz Homemade Beef Burger - Handpressed", "", "", "", "fresh", "", "JLB3", "", ""), 
	("ea x 8oz Hmade Beefburgers - Handpressed", "", "", "", "fresh", "", "JLB4", "", ""), 
	("ea x 2oz Homemade Beef Burgers", "", "", "", "fresh", "", "JLB6", "", ""), 
	("ea x 4oz Hmade Beefburgers", "", "", "", "fresh", "", "JLB7", "", ""), 
	("ea x 80vl 4oz Homemade Beef Burger - Allergy Free Seasoning", "", "", "", "fresh", "", "JLB71", "", ""), 
	("ea x 7oz Homemade Beef Burgers", "", "", "", "fresh", "", "JLB8", "", ""), 
	("ea x 6oz Hmade Beefburgers", "", "", "", "fresh", "", "JLB9", "", ""), 
	("ea x 3oz Homemade Chuck and Rump Burger", "", "", "", "fresh", "", "JLB92", "", ""), 
	("ea x 4oz Homemade Chuck and Rump Burger", "", "", "", "fresh", "", "JLB921", "", ""), 
	("ea x 6oz Homemade Chuck and Rump Burgers", "", "", "", "fresh", "", "JLB9211", "", ""), 
	("ea x 7oz Homemade Chuck and Rump Burger", "", "", "", "fresh", "", "JLB92111", "", ""), 
	("kgs x Minced Leg of Lamb", "", "", "", "fresh", "", "LA11", "", ""), 
	("kgs x Legs Lamb B&R", "", "", "", "fresh", "", "LA2", "", ""), 
	("kgs x B'less Leg Lamb Steaks", "", "", "", "fresh", "", "LA3", "", ""), 
	("kgs x B'less Lamb thigh", "", "", "", "fresh", "", "LA31", "", ""), 
	("kgs x Bone In Leg Lamb Steaks", "", "", "", "fresh", "", "LA311", "", ""), 
	("kgs Lamb Sweetbreads", "", "", "", "fresh", "", "LA3111", "", ""), 
	("kgs x Saddles Lamb B&R", "", "", "", "fresh", "", "LA4", "", ""), 
	("kgs x Shoulder of Lamb Bone In", "", "", "", "fresh", "", "LA41", "", ""), 
	("kgs x  Leg Lamb on the Bone", "", "", "", "fresh", "", "LA5", "", ""), 
	("kgs x NZ Legs Lamb B&R", "", "", "", "fresh", "", "LA71", "", ""), 
	("kgs x Lamb Bones", "", "", "", "fresh", "", "LA711", "", ""), 
	("kgs x Shoulders of Lamb B&R s/w", "", "", "", "fresh", "", "LA8", "", ""), 
	("kgs x English Lamb Noissettes", "", "", "", "fresh", "", "LA91", "", ""), 
	("ea x 200g Lamb Noisettes", "", "", "", "fresh", "", "LA911", "", ""), 
	("kgs x Whole Kentish Lamb", "", "", "", "fresh", "", "LA92", "", ""), 
	("kgs x Breast of Lamb", "", "", "", "fresh", "", "LA93", "", ""), 
	("kgs x Eye Loin Lamb Fillets", "", "", "", "fresh", "", "LA94", "", ""), 
	("kgs x British Lamb Chops", "", "", "", "fresh", "", "LA95", "", ""), 
	("kgs x Lamb Cutlets", "", "", "", "fresh", "", "LA96", "", ""), 
	("kgs x Whole Chine and End Deboned", "", "", "", "fresh", "", "LA97", "", ""), 
	("kgs x Diced Lamb", "", "", "", "fresh", "", "LA98", "", ""), 
	("kgs x Ovine Boneless Legs of Lamb", "", "", "", "fresh", "", "LA981", "", ""), 
	("kgs x NZ Lamb Neck Fillets", "", "", "", "fresh", "", "LA99", "", ""), 
	("kgs x Lamb Neck Fillets", "", "", "", "fresh", "", "LA990", "", ""), 
	("kgs x Stir Fry Lamb", "", "", "", "fresh", "", "LA991", "", ""), 
	("kgs x Barnsley Lamb Chops", "", "", "", "fresh", "", "LA992", "", ""), 
	("ea x 8-10oz Barnsley Chops", "", "", "", "fresh", "", "LA9921", "", ""), 
	("ea x 3 Bone Racks of Lamb Fr/Tr - SPECIAL OFFER", "", "", "", "fresh", "", "LA993", "", ""), 
	("ea x 4 Bone Racks of Lamb Fr/Tr", "", "", "", "fresh", "", "LA9931", "", ""), 
	("ea x 5 Bone Racks of Lamb Fr/Tr", "", "", "", "fresh", "", "LA99311", "", ""), 
	("ea x 6 Bone Racks of Lamb Fr/Tr", "", "", "", "fresh", "", "LA9933111", "", ""), 
	("ea x 7 Bone Racks of Lamb Fr/Tr", "", "", "", "fresh", "", "LA99331111", "", ""), 
	("kgs x Lamb Shanks", "", "", "", "fresh", "", "LA995", "", ""), 
	("ea x 7-8oz B'less Lamb Rumps", "", "", "", "fresh", "", "LA9971", "", ""), 
	("ea x 5-6oz B'less Lamb Rumps", "", "", "", "fresh", "", "LA99711", "", ""), 
	("kgs x D beef- halal", "", "", "", "fresh", "", "NOUBE2H", "", ""), 
	("kgs x mince beef- halal", "", "", "", "fresh", "", "NOUBE4H", "", ""), 
	("kgs x Best UK prime topside- halal", "", "", "", "fresh", "", "NOUBE6H", "", ""), 
	("pk x  Breaded Chicken Steaks (approx 11)", "", "", "", "fresh", "", "NOUCHB", "", ""), 
	("pk 2.5kgs Chicken Burger- HALAL", "", "", "", "fresh", "", "NOUCHBH", "", ""), 
	("ea x 8-9oz chicken breast fillets- halal", "", "", "", "fresh", "", "NOUCHR311H", "", ""), 
	("ea x 6-7oz chicken breast fillets- halal", "", "", "", "fresh", "", "NOUCHR31H", "", ""), 
	("kgs x chicken oyster thighs- halal", "", "", "", "fresh", "", "NOUCHR92H", "", ""), 
	("kgs x diced chicken 50/50- halal", "", "", "", "fresh", "", "NOUCHR941H", "", ""), 
	("kgs x diced chicken breast- halal", "", "", "", "fresh", "", "NOUCHR94H", "", ""), 
	("kgs x chicken wings- halal", "", "", "", "fresh", "", "NOUCHR95H", "", ""), 
	("kgs x Minced Chicken Breast HALAL - Added Cumberland Mix", "", "", "", "fresh", "", "NOUCHR96", "", ""), 
	("kgs x chicken drumsticks- halal", "", "", "", "fresh", "", "NOUCHR9H", "", ""), 
	("pk x 1.8kg Grated 80/20 Cheese", "", "", "", "fresh", "", "NOUDAR6", "", ""), 
	("pk x 2kg Grated Mild Cheddar (NOU)", "", "", "", "fresh", "", "NOUDAR61", "", ""), 
	("c/s 48 x 2oz Beef Burgers- FROZEN- HALAL", "", "", "", "fresh", "", "NOUJLB1H", "", ""), 
	("c/s 4 x 2.27kg 3/8 Frozen Chips", "", "", "", "fresh", "", "NOUKA1", "", ""), 
	("kgs x Mince lamb- halal", "", "", "", "fresh", "", "NOULA11H", "", ""), 
	("kgs x Diced Lamb - Halal", "", "", "", "fresh", "", "NOULA98H", "", ""), 
	("ea x 1lb Poultry Sausagemeat - FROZEN", "", "", "", "fresh", "", "NOUSS93", "", ""), 
	("kg x Diced Turkey - halal", "", "", "", "fresh", "", "NOUTKY4H", "", ""), 
	("kgs x turkey joints- halal", "", "", "", "fresh", "", "NOUTKY5H", "", ""), 
	("pk x 2.5kg Garden Peas", "", "", "", "fresh", "", "NOUVEG98", "", ""), 
	("pk x 2.5kg Diced Carrots", "", "", "", "fresh", "", "NOUVEG981", "", ""), 
	("pk x 2.5kg Sweetcorn", "", "", "", "fresh", "", "NOUVEG9811", "", ""), 
	("kgs x Sliced Lambs Liver", "", "", "", "fresh", "", "OFF1", "", ""), 
	("kgs x Pigs Ears", "", "", "", "fresh", "", "OFF10", "", ""), 
	("kgs x Pigs Trotters", "", "", "", "fresh", "", "OFF11", "", ""), 
	("kgs x Pigs Head", "", "", "", "fresh", "", "OFF111", "", ""), 
	("kgs x Diced Goat", "", "", "", "fresh", "", "OFF12", "", ""), 
	("kgs x Lambs Kidney", "", "", "", "fresh", "", "OFF2", "", ""), 
	("kgs x Pigs Liver", "", "", "", "fresh", "", "OFF3", "", ""), 
	("kgs x Duck Fat", "", "", "", "fresh", "", "OFF4", "", ""), 
	("kgs x Pigs Cheeks", "", "", "", "fresh", "", "OFF5", "", ""), 
	("kgs x Ox Tongues", "", "", "", "fresh", "", "OFF52", "", ""), 
	("kgs x Ox Kidneys", "", "", "", "fresh", "", "OFF6", "", ""), 
	("kgs x Chicken Livers", "", "", "", "fresh", "", "OFF7", "", ""), 
	("ea x 8oz tubs Chicken Livers", "", "", "", "fresh", "", "OFF71", "", ""), 
	("kgs x Ox Tails", "", "", "", "fresh", "", "OFF8", "", ""), 
	("kgs x Ox Cheeks - FROZEN", "", "", "", "fresh", "", "OFF9", "", ""), 
	("kgs x Ox Cheeks - FRESH", "", "", "", "fresh", "", "OFF91", "", ""), 
	("kgs x Ducks Liver", "", "", "", "fresh", "", "OFF99", "", ""), 
	("kgs x Minced Chuck / Minced Brisket S/W", "", "", "", "fresh", "", "PMBE4", "", ""), 
	("kgs x Local Leg of Pork-on the bone", "", "", "", "fresh", "", "PO1", "", ""), 
	("kgs x Pork Shank on the Bone", "", "", "", "fresh", "", "PO11", "", ""), 
	("kgs x Local Leg of Pork B&R", "", "", "", "fresh", "", "PO2", "", ""), 
	("kgs x Whole Pig (50-60kg)", "", "", "", "fresh", "", "PO3", "", ""), 
	("kgs x Whole Pig (40-45kg)", "", "", "", "fresh", "", "PO31", "", ""), 
	("kgs x Local Loin of Pork B&R", "", "", "", "fresh", "", "PO4", "", ""), 
	("kgs x Boneless Pork Collars", "", "", "", "fresh", "", "PO41", "", ""), 
	("kgs x Bacon Loin of Pork", "", "", "", "fresh", "", "PO411", "", ""), 
	("kgs x Local Shoulder of Pork B&R M/W", "", "", "", "fresh", "", "PO5", "", ""), 
	("kgs x Boston Pork Butt", "", "", "", "fresh", "", "PO51", "", ""), 
	("kgs x Whole Shoulder of Pork", "", "", "", "fresh", "", "PO52", "", ""), 
	("kgs x B'less Pork Steaks", "", "", "", "fresh", "", "PO6", "", ""), 
	("ea x 6oz Bacon Loin Steaks", "", "", "", "fresh", "", "PO61", "", ""), 
	("kgs x Pork Skin", "", "", "", "fresh", "", "PO611", "", ""), 
	("kgs x 10oz Dry Cured Bacon Steaks", "", "", "", "fresh", "", "PO62", "", ""), 
	("kgs x Diced Leg of Pork", "", "", "", "fresh", "", "PO7", "", ""), 
	("kgs x Diced Shoulder of Pork", "", "", "", "fresh", "", "PO71", "", ""), 
	("kgs x  Pork Chops", "", "", "", "fresh", "", "PO8", "", ""), 
	("ea x 10oz Pork Chops", "", "", "", "fresh", "", "PO81", "", ""), 
	("ea x Pork Tommahawk Steaks", "", "", "", "fresh", "", "PO811", "", ""), 
	("kgs x 6-8oz Pork Chops Fr/Tr   S/W", "", "", "", "fresh", "", "PO8111", "", ""), 
	("kgs x Pork Fillet", "", "", "", "fresh", "", "PO91", "", ""), 
	("kgs x Pork Escolapes", "", "", "", "fresh", "", "PO911", "", ""), 
	("kgs x Stir Fry Pork", "", "", "", "fresh", "", "PO92", "", ""), 
	("kgs x Belly Pork Slices", "", "", "", "fresh", "", "PO93", "", ""), 
	("kgs x Whole Belly Pork", "", "", "", "fresh", "", "PO94", "", ""), 
	("kgs x Whole Pork Belly - Skinned and Boned", "", "", "", "fresh", "", "PO941", "", ""), 
	("kgs x Whole Pork Belly - Deboned", "", "", "", "fresh", "", "PO9411", "", ""), 
	("kgs x Whole Pork Belly Boned and Rolled", "", "", "", "fresh", "", "PO94111", "", ""), 
	
	("kgs x Sussex Bred Pork Belly Skinned Boned & Rolled S/W", "", "", "", "fresh", "", "PO9411111", "", ""), 
	("kgs x Pork Spare Ribs", "", "", "", "fresh", "", "PO95", "", ""), 
	("kgs x Pork St Luis Style Ribs", "", "", "", "fresh", "", "PO951", "", ""), 
	("kgs x Minced Lean Pork", "", "", "", "fresh", "", "PO96", "", ""), 
	("kgs Pork Bones", "", "", "", "fresh", "", "PO97", "", ""), 
	("kgs x Portioned Baby Back Ribs", "", "", "", "fresh", "", "PO971", "", ""), 
	("kgs x Baby Back Ribs", "", "", "", "fresh", "", "PO9711", "", ""), 
	("pkt (2.27kgs),Red Tractor R'less Back Bacon", "", "", "", "fresh", "", "RTBAC3", "", ""), 
	("c/s (4 x 2.27kgs),Red Tractor R'less Back Bacon", "", "", "", "fresh", "", "RTBAC31", "", ""), 
	("kgs x Red Tractor Diced Beef", "", "", "", "fresh", "", "RTBE2", "", ""), 
	("kgs x Red Tractor Diced Beef - FROZEN", "", "", "", "fresh", "", "RTBE3", "", ""), 
	("kgs x Red Tractor Mince Beef- FROZEN", "", "", "", "fresh", "", "RTBE4", "", ""), 
	("kgs x Organic Minced Beef - FROZEN", "", "", "", "fresh", "", "RTBE411", "", ""), 
	("kgs x R/T Topside", "", "", "", "fresh", "", "RTBE7", "", ""), 
	("kgs Red Tractor Beef Stir-fry", "", "", "", "fresh", "", "RTBE997", "", ""), 
	("pkts (12 x 85g),UK Breaded Chicken Steaks", "", "", "", "fresh", "", "RTCC01", "", ""), 
	("pkts (1kgs),UK Breaded Chicken Goujons - Southern", "", "", "", "fresh", "", "RTCC02", "", ""), 
	("pkts (1kgs),UK Breaded Chicken Goujons - Hot & Spicy", "", "", "", "fresh", "", "RTCC03", "", ""), 
	("ea. Red Tractor Chicken Legs - FROZEN", "", "", "", "fresh", "", "RTCH1", "", ""), 
	("kgs x Red Tractor Whole Fresh Chicken", "", "", "", "fresh", "", "RTCH2", "", ""), 
	("kgs x Red tractor Chicken Breast", "", "", "", "fresh", "", "RTCH3", "", ""), 
	("ea. Red Tractor 6/7oz Chicken Breast Fillets", "", "", "", "fresh", "", "RTCH31", "", ""), 
	("x 1kgs R/T Chicken Goujon - Plain - FROZEN", "", "", "", "fresh", "", "RTCH5", "", ""), 
	("pkt (1kgs),R/T Chicken Goujon GLAZED - S/ Fried Frozen", "", "", "", "fresh", "", "RTCH51", "", ""), 
	("kgs x Red Tractor Chicken Drumsticks - FROZEN", "", "", "", "fresh", "", "RTCH9", "", ""), 
	("kgs x Red Tractor Chicken Oyster Thighs - FROZEN", "", "", "", "fresh", "", "RTCH91", "", ""), 
	("ea. Red Tractor Chicken Thighs B'less", "", "", "", "fresh", "", "RTCH92", "", ""), 
	("kgs x R/Tr Chicken Breast Strips", "", "", "", "fresh", "", "RTCH93", "", ""), 
	("x  Halal Mince Beef - FROZEN", "", "", "", "fresh", "", "RTCH931", "", ""), 
	("Kgs x Red Tractor Diced Chicken Breast", "", "", "", "fresh", "", "RTCH94", "", ""), 
	("kgs x Red Tractor Diced Chicken Mix (50/50)", "", "", "", "fresh", "", "RTCH941", "", ""), 
	("kgs x Diced Chicken 50/50 - FROZEN", "", "", "", "fresh", "", "RTCH95", "", ""), 
	("kgs x 3-Bone Red Tractor Chicken Wings - FROZEN", "", "", "", "fresh", "", "RTCH951", "", ""), 
	("c/s 24x4oz Hmade Beef Burgers - Red Tractor FROZEN", "", "", "", "fresh", "", "RTJL1", "", ""), 
	("c/s 48x2oz Hmade Beef Burgers - Red Tractor FROZEN", "", "", "", "fresh", "", "RTJL2", "", ""), 
	
	("kgs x  Diced UK Turkey Breast Roll (Red Tractor)", "", "", "", "fresh", "", "RTTK4", "", ""), 
	("kgs x UK Turkey Breast Roll (Red Tractor)", "", "", "", "fresh", "", "RTTK5", "", ""), 
	("kgs x  Minced UK Turkey Breast Roll (Red Tractor)", "", "", "", "fresh", "", "RTTKY3", "", ""), 
	("ea. 4 x 15g Chicken Thigh Skewer", "", "", "", "fresh", "", "SKWCHI", "", ""), 
	("ea 3 x 25g Chicken Thigh Skewer", "", "", "", "fresh", "", "SKWCHI1", "", ""), 
	("ea 2 x 25g Chicken Thigh Skewer", "", "", "", "fresh", "", "SKWCHI2", "", ""), 
	("ea 4 x 15g Lamb Rump Skewer", "", "", "", "fresh", "", "SKWLA", "", ""), 
	("X 16oz T-Bone Steak", "", "", "", "fresh", "", "SP0FF10", "", ""), 
	("x 1 x 250g salted butter  (Free offer)", "", "", "", "fresh", "", "SP0FF11", "", ""), 
	("c/s 4 x 2.25kg 9.5mm Premium Extra Crunchy Coated Fries", "", "", "", "fresh", "", "SPOFF01", "", ""), 
	("c/s 4 x 2.27kg Steakhouse Chips", "", "", "", "fresh", "", "SPOFF02", "", ""), 
	("c/s 178 x 28g Italian Style Meatballs", "", "", "", "fresh", "", "SPOFF03", "", ""), 
	("*EMPTY NAME REPLACE*", "", "", "", "fresh", "", "SPOFF04", "", ""), 
	("*EMPTY NAME REPLACE*", "", "", "", "fresh", "", "SPOFF05", "", ""), 
	("*EMPTY NAME REPLACE*", "", "", "", "fresh", "", "SPOFF06", "", ""), 
	("*EMPTY NAME REPLACE*", "", "", "", "fresh", "", "SPOFF07", "", ""), 
	("SPECIAL OFFER", "", "", "", "fresh", "", "SPOFF08", "", ""), 
	("SPECIAL OFFER", "", "", "", "fresh", "", "SPOFF09", "", ""), 
	("10 x 4oz Homemade Beef Burgers", "", "", "", "fresh", "", "SPOFF10", "", ""), 
	("kgs x Whole Eng Free Range Stag Fresh Turkey 12kg+", "", "", "", "fresh", "", "TKY1", "", ""), 
	("kgs x Whole Turkey Boned & Rolled", "", "", "", "fresh", "", "TKY101", "", ""), 
	
	("kgs x Turkey Breast Butterfly - TIED", "", "", "", "fresh", "", "TKY21", "", ""), 
	("kgs x Stir Fry Turkey", "", "", "", "fresh", "", "TKY3", "", ""), 
	("kgs x Diced Turkey Breast Meat", "", "", "", "fresh", "", "TKY4", "", ""), 
	("kgs x Single Turkey Breast Netted", "", "", "", "fresh", "", "TKY5", "", ""), 
	("kgs x Turkey Breast Butterfly - FROZEN (Nourish)", "", "", "", "fresh", "", "TKY51", "", ""), 
	("kgs Turkey Breast Joints wrapped in streaky bacon", "", "", "", "fresh", "", "TKY511", "", ""), 
	("kgs x Single Turkey Breast Netted Frozen", "", "", "", "fresh", "", "TKY5F", "", ""), 
	("kgs x Minced Turkey Breast", "", "", "", "fresh", "", "TKY6", "", ""), 
	("Kgs x Minced Turkey- Halal", "", "", "", "fresh", "", "TKY6H", "", ""), 
	("kgs x Fresh UK Hen Turkey 4kgs+", "", "", "", "fresh", "", "TKY7", "", ""), 
	("kgs  x Turkey Escalopes", "", "", "", "fresh", "", "TKY8", "", ""), 
	("kgs x Boneless Turkey Thigh Joints", "", "", "", "fresh", "", "TKY81", "", ""), 
	("kgs x UK Gammon Joint B&R", "", "", "", "fresh", "", "UKBAC2", "", ""), 
	("pk x 2.27kg Premium Back Bacon", "", "", "", "fresh", "", "UKBAC3", "", ""), 
	("pk x 2.27kg Premium Smoked Back Bacon", "", "", "", "fresh", "", "UKBAC4", "", ""), 
	("pk x 2.27kg Premium Streaky Bacon", "", "", "", "fresh", "", "UKBAC8", "", ""), 
	("pk x 2.27kg Premium Smoked Streaky Bacon", "", "", "", "fresh", "", "UKBAC81", "", ""), 
	("kgs x UK Diced Beef", "", "", "", "fresh", "", "UKBE2", "", ""), 
	("kgs x UK 95vl Minced Beef", "", "", "", "fresh", "", "UKBE4", "", ""), 
	("kgs x UK Beef Topside", "", "", "", "fresh", "", "UKBE6", "", ""), 
	("kgs x UK Silverside/Roasting Joint", "", "", "", "fresh", "", "UKBE7", "", ""), 
	("kgs x UK Flat Beef Brisket", "", "", "", "fresh", "", "UKBE9", "", ""), 
	("kgs x UK Stir Fry Beef", "", "", "", "fresh", "", "UKBE97", "", ""), 
	("pk x (10-12 x 85g),UK Chicken Steaks", "", "", "", "fresh", "", "UKCH2", "", ""), 
	("pk x 1kgs UK Breaded Chicken Goujons", "", "", "", "fresh", "", "UKCH3", "", ""), 
	("ea x Oyster Cut Chicken Leg - FRESH", "", "", "", "fresh", "", "UKCHR1", "", ""), 
	("kgs x UK Whole Chicken", "", "", "", "fresh", "", "UKCHR2", "", ""), 
	("ea x UK Skin on Chicken Breast", "", "", "", "fresh", "", "UKCHR21", "", ""), 
	("ea x UK 6/7oz Chicken Breast Fillet - Butterfly", "", "", "", "fresh", "", "UKCHR301", "", ""), 
	("ea x UK 6/7oz Chicken Breast", "", "", "", "fresh", "", "UKCHR31", "", ""), 
	("ea x 5oz Chicken Breast", "", "", "", "fresh", "", "UKCHR311", "", ""), 
	("ea x UK 6/7oz Chicken Fillet Butterfly - Cut all the way through", "", "", "", "fresh", "", "UKCHR32", "", ""), 
	("ea x UK 100-140g Chicken Fillet", "", "", "", "fresh", "", "UKCHR33", "", ""), 
	(" ea x UK Skin on Chicken Fillet - french trimmed", "", "", "", "fresh", "", "UKCHR410", "", ""), 
	("kgs x UK Chicken Drumsticks - FRESH", "", "", "", "fresh", "", "UKCHR9", "", ""), 
	("kgs x UK Chicken Oyster Thighs", "", "", "", "fresh", "", "UKCHR92", "", ""), 
	("kgs x UK Skin on Boneless Chicken Thighs", "", "", "", "fresh", "", "UKCHR920", "", ""), 
	("ea x 60-80g UK Skin on Boneless Chicken Thighs", "", "", "", "fresh", "", "UKCHR9200", "", ""), 
	("ea x 110-140g UK Skin on Boneless Chicken Thighs", "", "", "", "fresh", "", "UKCHR92000", "", ""), 
	("kgs x UK Diced Chicken Thigh Meat", "", "", "", "fresh", "", "UKCHR9201", "", ""), 
	("kgs x UK Skinless Boneless Chicken Thigh Meat", "", "", "", "fresh", "", "UKCHR9202", "", ""), 
	("kgs x UK Chicken Breast Fillets", "", "", "", "fresh", "", "UKCHR93", "", ""), 
	("kgs x UK Diced Chicken Breast", "", "", "", "fresh", "", "UKCHR94", "", ""), 
	("kgs x UK Diced Chicken Breast & Thigh", "", "", "", "fresh", "", "UKCHR941", "", ""), 
	("kgs x UK Chicken Wings", "", "", "", "fresh", "", "UKCHR95", "", ""), 
	("ea x 110-130g UK Chicken Drumsticks - FRESH", "", "", "", "fresh", "", "UKCHR99", "", ""), 
	("kgs x UK Stir Fry Chicken Breast", "", "", "", "fresh", "", "UKCHR999", "", ""), 
	("ea x 1.3kg Stick of Black Pudding", "", "", "", "fresh", "", "UKCME92", "", ""), 
	("pk x 454g Butchers Sliced Gammon Ham", "", "", "", "fresh", "", "UKCME9811", "", ""), 
	("pk x 500g Sliced Cooked Beef", "", "", "", "fresh", "", "UKCME99", "", ""), 
	("pk x 500g Sliced Cooked Turkey", "", "", "", "fresh", "", "UKCME991", "", ""), 
	("kgs x UK Chicken Wings - BBQ Glaze", "", "", "", "fresh", "", "UKGBCHR95", "", ""), 
	("kgs x UK Chicken Wings - Garlic & Butter", "", "", "", "fresh", "", "UKGGCHR95", "", ""), 
	("ea x 4lb Lancashire Haggis", "", "", "", "fresh", "", "UKHAG1", "", ""), 
	("ea x 4lb Mcsween Haggis", "", "", "", "fresh", "", "UKHAG2", "", ""), 
	("kgs x UK/IE Hand Diced Beef - HALAL", "", "", "", "fresh", "", "UKHBE2", "", ""), 
	("kgs x UK/IE 95vl Minced Beef - Halal", "", "", "", "fresh", "", "UKHBE4", "", ""), 
	("kgs x UK/IE Stir Fry Beef   - HALAL", "", "", "", "fresh", "", "UKHBE9", "", ""), 
	("ea x UK 2oz Homemade Beef Burger - HALAL", "", "", "", "fresh", "", "UKHJLB2", "", ""), 
	("ea x UK/IE 4oz Homemade Beef Burger - HALAL", "", "", "", "fresh", "", "UKHJLB7", "", ""), 
	("kgs x Minced Leg of Lamb - HALAL", "", "", "", "fresh", "", "UKHLA1", "", ""), 
	("ea x UK 2oz Homemade Beef Burgers", "", "", "", "fresh", "", "UKJLB2", "", ""), 
	("ea x 4oz UK Homemade Beef Burgers", "", "", "", "fresh", "", "UKJLB7", "", ""), 
	("ea x UK 6oz Homemade Beef Burgers", "", "", "", "fresh", "", "UKJLB9", "", ""), 
	("kgs x UK Minced Leg of Lamb", "", "", "", "fresh", "", "UKLA1", "", ""), 
	("kgs x UK Leg of Lamb B&R  S/W", "", "", "", "fresh", "", "UKLA2", "", ""), 
	("kgs x UK Shoulders of Lamb B&R s/w", "", "", "", "fresh", "", "UKLA8", "", ""), 
	("kgs x UK Diced Lamb", "", "", "", "fresh", "", "UKLA98", "", ""), 
	("kgs x UK Leg of Pork B&R", "", "", "", "fresh", "", "UKPO2", "", ""), 
	("kgs x UK Loin of Pork B&R", "", "", "", "fresh", "", "UKPO4", "", ""), 
	("kgs x UK Shoulder of Pork B&R", "", "", "", "fresh", "", "UKPO5", "", ""), 
	("kgs x UK Pork Collar", "", "", "", "fresh", "", "UKPO51", "", ""), 
	("kgs x UK Boneless Pork Steaks", "", "", "", "fresh", "", "UKPO6", "", ""), 
	("ea x UK 3oz B'less Pork Steaks", "", "", "", "fresh", "", "UKPO61", "", ""), 
	("kgs x Pork Spare Ribs", "", "", "", "fresh", "", "UKPO7", "", ""), 
	("kgs x UK Diced Leg of Pork", "", "", "", "fresh", "", "UKPO8", "", ""), 
	("kgs x Whole Pork Belly (spec)", "", "", "", "fresh", "", "UKPO94", "", ""), 
	("kgs x UK Minced Leg of Pork", "", "", "", "fresh", "", "UKPO96", "", ""), 
	("kgs x UK Stir Fry Pork Leg", "", "", "", "fresh", "", "UKPO97", "", ""), 
	("ea x 2oz Homemade Pork Sausage Pattie", "", "", "", "fresh", "", "UKSS01", "", ""), 
	("c/s x Poultry 8's- HALAL", "", "", "", "fresh", "", "UKSS10", "", ""), 
	("ea x 5lb Fresh Tray UK Cumberland 8s", "", "", "", "fresh", "", "UKSS21", "", ""), 
	("pk 2.27kg x Fresh PW Poultry 8s", "", "", "", "fresh", "", "UKSS211", "", ""), 
	("pk x 5lb Fresh Tray UK Cumberland 6s", "", "", "", "fresh", "", "UKSS2111", "", ""), 
	("ea x 1lb Fresh UK Cumberland Sausagemeat", "", "", "", "fresh", "", "UKSS51", "", ""), 
	("c/s 4.54kgs RSPCA Frozen Pork 4s", "", "", "", "fresh", "", "UKSS6", "", ""), 
	("c/s 4.54kgs RSPCA Frozen Pork 8s", "", "", "", "fresh", "", "UKSS61", "", ""), 
	("c/s 4.54kgs RSPCA Frozen Pork 16s", "", "", "", "fresh", "", "UKSS611", "", ""), 
	("c/s (160 x 28g),Mediterranean Style Beef & Pork Meatballs - FROZEN", "", "", "", "fresh", "", "UKSS7", "", ""), 
	("c/s (160 x 28g),Swedish Style Chicken & Beef Meatballs - FROZEN", "", "", "", "fresh", "", "UKSS71", "", ""), 
	("c/s (60 x 30g),UK Beef Meatballs FROZEN", "", "", "", "fresh", "", "UKSS8", "", ""), 
	("ea x 1.6kg Stick of Chorizo", "", "", "", "fresh", "", "UKSS94", "", ""), 
	("kgs x UK Chicken Wings Tandoori Glaze", "", "", "", "fresh", "", "UKTGCHR95", "", ""), 
	("ea x UK 3oz Turkey Escalopes", "", "", "", "fresh", "", "UKTKY2", "", ""), 
	("ea x UK 4oz Turkey Breast Escalope", "", "", "", "fresh", "", "UKTKY3", "", ""), 
	("ea x UK 5/6oz Turkey Breast Escalope", "", "", "", "fresh", "", "UKTKY31", "", ""), 
	("kgs x UK Diced Turkey Breast", "", "", "", "fresh", "", "UKTKY4", "", ""), 
	("kgs x UK Single Turkey Breast Netted", "", "", "", "fresh", "", "UKTKY5", "", ""), 
	("kgs x UK Minced Turkey Breast", "", "", "", "fresh", "", "UKTKY6", "", ""), 
	("kgs x UK Turkey Breast Escalopes", "", "", "", "fresh", "", "UKTKY7", "", ""), 
	("kgs x UK Stir Fry Turkey Breast", "", "", "", "fresh", "", "UKTKY9", "", ""), 
	("kgs x UK 95vl Minced Beef - Vac Pack", "", "", "", "fresh", "", "UKVBE4", "", ""), 
	("ea x approx 60g chicken breast pieces", "", "", "", "fresh", "", "WSMCHR31", "", ""), 
	("kgs x Homemade Cumberland Sausagemeat", "", "", "", "fresh", "", "WSMSS51", "", ""), 
	("ea x 1kgs Homemade Beef Sausagemeat", "", "", "", "fresh", "", "WSMSS511", "", ""), 
	("2kg Gammon Joint x", "", "", "", "fresh", "", "ZBAC2", "", ""), 
	("3kg Gammon Joint x", "", "", "", "fresh", "", "ZBAC21", "", ""), 
	("4kg Gammon Joint x", "", "", "", "fresh", "", "ZBAC211", "", ""), 
	("5kg Gammon Joint x", "", "", "", "fresh", "", "ZBAC2111", "", ""), 
	("2kg Topside Joint x", "", "", "", "fresh", "", "ZBE6", "", ""), 
	("3kg Topside Joint x", "", "", "", "fresh", "", "ZBE61", "", ""), 
	("4kgs Topside Joint x", "", "", "", "fresh", "", "ZBE611", "", ""), 
	("5kg Topside Joint x", "", "", "", "fresh", "", "ZBE6111", "", ""), 
	("4kg Rump of Beef - Trimmed & Tied  x", "", "", "", "fresh", "", "ZBE9", "", ""), 
	("Whole Beef Striploin / Complete Trim + Burgers", "", "", "", "fresh", "", "ZBE989", "", ""), 
	("8kg+ Striploin of Beef Trimmed x", "", "", "", "fresh", "", "ZBE9891", "", ""), 
	("4kg Striploin Joint x", "", "", "", "fresh", "", "ZBE99", "", ""), 
	("5-6kg Whole Premium Striploin x", "", "", "", "fresh", "", "ZBE998", "", ""), 
	("6-7kg Whole Premium Striploin x", "", "", "", "fresh", "", "ZBE9981", "", ""), 
	("3.5kg Striploin of Beef - Larger Trimmed S/W x", "", "", "", "fresh", "", "ZBE99811", "", ""), 
	("Whole Beef Striploin - Larder Trimmed S/W x", "", "", "", "fresh", "", "ZBE998111", "", ""), 
	("Whole Beef Striploin - Trimmed and Tied S/W x", "", "", "", "fresh", "", "ZBE9981111", "", ""), 
	("Calves Feet Split x", "", "", "", "fresh", "", "ZBEEF21", "", ""), 
	("300-350g Frozen Polish Duck Legs", "", "", "", "fresh", "", "ZCH8", "", ""), 
	("1.2kg Whole Chicken x", "", "", "", "fresh", "", "ZCHR2", "", ""), 
	("1.8kg Whole Chicken  x", "", "", "", "fresh", "", "ZCHR21", "", ""), 
	("1.5kg Whole Chicken x", "", "", "", "fresh", "", "ZCHR211", "", ""), 
	("1.2kg Whole Chicken Cut in Half x", "", "", "", "fresh", "", "ZCHR2111", "", ""), 
	("1.5kg Whole Chicken Cut in Half x", "", "", "", "fresh", "", "ZCHR21111", "", ""), 
	("Whole Poussin - Spatchcock", "", "", "", "fresh", "", "ZCHR6", "", ""), 
	("kgs x 250/280g UK Gressingham Duck Breast", "", "", "", "fresh", "", "ZCHR91", "", ""), 
	("ea x 200-220g Frozen Polish Duck Breast", "", "", "", "fresh", "", "ZCHR911", "", ""), 
	("kgs x 8/9oz Chicken Breasts Butterflied - Goujons Sep", "", "", "", "fresh", "", "ZCHR93", "", ""), 
	("ea x 8oz Sirloin Steak - HALAL", "", "", "", "fresh", "", "ZHBE98", "", ""), 
	("ea x Skin on Chicken Fillet - HALAL", "", "", "", "fresh", "", "ZHCHR41", "", ""), 
	("Large Leg of Lamb B&R HALAL x", "", "", "", "fresh", "", "ZHLA2", "", ""), 
	("ea x 3 x 25g Chicken Thigh Kebab", "", "", "", "fresh", "", "ZHSKW1", "", ""), 
	("Shoulder of Lamb B&R x", "", "", "", "fresh", "", "ZLA8", "", ""), 
	
	("Shoulder of Lamb - Bone In x", "", "", "", "fresh", "", "ZLA811", "", ""), 
	("Lamb Chops - Packed in 3s x", "", "", "", "fresh", "", "ZLA95", "", ""), 
	("1' Cube of Lamb x", "", "", "", "fresh", "", "ZLA98", "", "", ""), 
	("2kg Leg of Pork B&R x", "", "", "", "fresh", "", "ZPO2", "", "", ""), 
	("3kg Leg of Pork B&R x", "", "", "", "fresh", "", "ZPO21", "", "", ""), 
	("4kg Leg of Pork B&R x", "", "", "", "fresh", "", "ZPO211", "", "", ""), 
	("5kg Pork Leg B&R x", "", "", "", "fresh", "", "ZPO2111", "", "", ""), 
	("2kg Loin of Pork B&R x", "", "", "", "fresh", "", "ZPO4", "", "", ""), 
	("3kg Loin of Pork B&R x", "", "", "", "fresh", "", "ZPO41", "", "", ""), 
	("4kg Loin of Pork B&R x", "", "", "", "fresh", "", "ZPO411", "", "", ""), 
	("5kg Loin of Pork B&R x", "", "", "", "fresh", "", "ZPO4111", "", "", ""), 
	("Whole Rindless Pork Loin x", "", "", "", "fresh", "", "ZPO41111", "", "", ""), 
	("Whole Loin of Pork - Skinned and Tied x", "", "", "", "fresh", "", "ZPO411111", "", "", ""), 
	("Rindless Pork Loin, Into 0.5cm Medallions + Mince", "", "", "", "fresh", "", "ZPO4Z", "", "", ""), 
	("3kg Shoulder of Pork B&R x", "", "", "", "fresh", "", "ZPO5", "", "", ""), 
	("5kg Shoulder or Pork B&R x", "", "", "", "fresh", "", "ZPO51", "", "", ""), 
	("Boneless Pork Shoulder Cut into 4", "", "", "", "fresh", "", "ZPO511", "", "", ""), 
	("4kgs Pork Shoulder B&R x", "", "", "", "fresh", "", "ZPO52", "", "", ""), 
	("ea x 5/6oz Pork Steak", "", "", "", "fresh", "", "ZPO6", "", "", ""), 
	("ea x 7/8oz Pork Steak", "", "", "", "fresh", "", "ZPO61", "", "", ""), 
	("Dry Cured Bacon Loin x", "", "", "", "fresh", "", "ZPO63", "", "", ""), 
	("ea x 8oz Pork Chops", "", "", "", "fresh", "", "ZPO8", "", "", ""), 
	("Boneless Pork Belly Cut into 4", "", "", "", "fresh", "", "ZPO94", "", "", ""), 
	("Whole Pork Belly x", "", "", "", "fresh", "", "ZPO941", "", "", ""), 
	("Whole Pork Belly - Deboned x", "", "", "", "fresh", "", "ZPO9411", "", "", ""), 
	("Whole Pork Belly, Boned and Rolled x", "", "", "", "fresh", "", "ZPO94111", "", "", ""), 
	("Whole Pork Belly - Skinned, Boned and Rolled x", "", "", "", "fresh", "", "ZPO941111", "", "", ""), 
	("Whole Pork Belly Flat, Skinned and Boned x", "", "", "", "fresh", "", "ZPO9411111", "", "")
  ]

errord_products = [
    ("Shoulder of Lamb - Deboned not Rolled x", "", "", "", "fresh", "", "ZLA81", "", ""), 
    ("kgs x Turkey Carvery Crowns - Bone in 8kg+", "", "", "", "fresh", "", "TKY2", "", ""), 
    ("kgs x RSPCA O/R O/B Pork Loins - R'less B&R", "", "", "", "fresh", "", "RTPO4", "", ""), 
	  ("kgs x RSPCA O/R O/B Pork Collars - R'less", "", "", "", "fresh", "", "RTPO41", "", ""), 
    ("kgs x Whole Pork Belly - Skinned Boned and Rolled", "", "", "", "fresh", "", "PO941111", "", ""), 
]


if __name__ == "__main__":
    insert_to_database();
