from products import insert_product


def insert_to_database():
  for product in products:
    insert_product(product[0], product[1], product[2], product[3], product[4], product[5], product[6], product[7], product[8])

products = [('Topside', 0, 0, 0, 'fresh', 'beef', '', '', 'kilo'),
('Silverside', 0, 0, 0, 'fresh', 'beef', '', '', 'kilo'),
('Brisket', 0, 0, 0, 'fresh', 'beef', '', '', 'kilo'),
('Skirts', 0, 0, 0, 'fresh', 'beef', '', '', 'kilo'),
('Frozen 95vl', 0, 0, 0, 'fresh', 'beef', '', '', 'kilo'),
('Fresh 95vl', 0, 0, 0, 'fresh', 'beef', '', '', 'kilo'),
('85vl', 0, 0, 0, 'fresh', 'beef', '', '', 'kilo'),
('Blades', 0, 0, 0, 'fresh', 'beef', '', '', 'kilo'),
('Chuck', 0, 0, 0, 'fresh', 'beef', '', '', 'kilo'),
('Fore Rib', 0, 0, 0, 'fresh', 'beef', '', '', 'kilo'),
('Pressed Fat', 0, 0, 0, 'fresh', 'beef', '', '', 'kilo'),
('Diced Beef', 0, 0, 0, 'fresh', 'beef', '', '', 'kilo'),
('Rump', 0, 0, 0, 'fresh', 'beef', '', '', 'kilo'),
('Fillet', 0, 0, 0, 'fresh', 'beef', '', '', 'kilo'),
('Fillet Tails', 0, 0, 0, 'fresh', 'beef', '', '', 'kilo'),
('Striploins', 0, 0, 0, 'fresh', 'beef', '', '', 'kilo'),
('Nerve Ends', 0, 0, 0, 'fresh', 'beef', '', '', 'kilo'),
('Rleye-UK', 0, 0, 0, 'fresh', 'beef', '', '', 'kilo'),
('8kg + Striploin', 0, 0, 0, 'fresh', 'beef', '', '', 'kilo'),
('Rump Trim', 0, 0, 0, 'fresh', 'beef', '', '', 'kilo'),
('Fat Trim', 0, 0, 0, 'fresh', 'beef', '', '', 'kilo'),
('Burger Mix', 0, 0, 0, 'fresh', 'beef', '', '', 'kilo'),
('Beef SHin', 0, 0, 0, 'fresh', 'beef', '', '', 'kilo'),

('Mutton Leg', 0, 0, 0, 'fresh', 'lamb', '', '', 'kilo'),
('Lamb Legs', 0, 0, 0, 'fresh', 'lamb', '', '', 'kilo'),
('Lamb Breasts', 0, 0, 0, 'fresh', 'lamb', '', '', 'kilo'),
('Lamb Saddles', 0, 0, 0, 'fresh', 'lamb', '', '', 'kilo'),
('Lamb Trim', 0, 0, 0, 'fresh', 'lamb', '', '', 'kilo'),
('Lamb Liver', 0, 0, 0, 'fresh', 'lamb', '', '', 'kilo'),
('Lamb Kidney', 0, 0, 0, 'fresh', 'lamb', '', '', 'kilo'),
('Lamb Shank', 0, 0, 0, 'fresh', 'lamb', '', '', 'kilo'),
('Lamb Chops', 0, 0, 0, 'fresh', 'lamb', '', '', 'kilo'),
('Diced Lamb', 0, 0, 0, 'fresh', 'lamb', '', '', 'kilo'),
('Barnsley Chops', 0, 0, 0, 'fresh', 'lamb', '', '', 'kilo'),

('R/Less Loin', 0, 0, 0, 'fresh', 'pork', '', '', 'kilo'),
('B/Less Leg', 0, 0, 0, 'fresh', 'pork', '', '', 'kilo'),
('Pork Collar', 0, 0, 0, 'fresh', 'pork', '', '', 'kilo'),
('Pork Trim', 0, 0, 0, 'fresh', 'pork', '', '', 'kilo'),
('Short Loin', 0, 0, 0, 'fresh', 'pork', '', '', 'kilo'),
('Pork Cheek', 0, 0, 0, 'fresh', 'pork', '', '', 'kilo'),
('Pork Fillet', 0, 0, 0, 'fresh', 'pork', '', '', 'kilo'),
('Pork SKin', 0, 0, 0, 'fresh', 'pork', '', '', 'kilo'),
('Short Rib', 0, 0, 0, 'fresh', 'pork', '', '', 'kilo'),
('Pork Shoulders B/in', 0, 0, 0, 'fresh', 'pork', '', '', 'kilo'),
('Belly', 0, 0, 0, 'fresh', 'pork', '', '', 'kilo'),
('Gammon Hock', 0, 0, 0, 'fresh', 'pork', '', '', 'kilo'),
('Gammon beef 10oz', 0, 0, 0, 'fresh', 'pork', '', '', 'pack'),
('Gammon beef 8oz', 0, 0, 0, 'fresh', 'pork', '', '', 'pack'),
('Smoked Gammon', 0, 0, 0, 'fresh', 'pork', '', '', 'kilo'),
('Gammon (bacon?)', 0, 0, 0, 'fresh', 'pork', '', '', 'kilo'),
('Cumberland Sausages 8s', 0, 0, 0, 'fresh', 'pork', '', '', 'kilo'),
('Cumberland Sausages 8s', 0, 0, 0, 'fresh', 'pork', '', '', 'kilo'),
('Gammon Slipper', 0, 0, 0, 'fresh', 'pork', '', '', 'kilo'),

('50/50', 0, 0, 0, 'fresh', 'poultry', '', '', 'kilo'),
('Duck Breasts', 0, 0, 0, 'fresh', 'poultry', '', '', 'kilo'),
('Duck Legs', 0, 0, 0, 'fresh', 'poultry', '', '', 'kilo'),
('Turkey Thigh', 0, 0, 0, 'fresh', 'poultry', '', '', 'kilo'),
('EU Thigh Meat', 0, 0, 0, 'fresh', 'poultry', '', '', 'kilo'),
('1.8', 0, 0, 0, 'fresh', 'poultry', '', '', 'kilo'),
('170-200', 0, 0, 0, 'fresh', 'poultry', '', '', 'kilo'),
('200-300', 0, 0, 0, 'fresh', 'poultry', '', '', 'kilo'),
('Thigh Meat', 0, 0, 0, 'fresh', 'poultry', '', '', 'kilo'),
('UK Breast', 0, 0, 0, 'fresh', 'poultry', '', '', 'kilo'),
('Uk Thigh Meat', 0, 0, 0, 'fresh', 'poultry', '', '', 'kilo'),
('UK Skin on Thigh', 0, 0, 0, 'fresh', 'poultry', '', '', 'kilo'),
('Oyster Thigh', 0, 0, 0, 'fresh', 'poultry', '', '', 'kilo'),
('Diced 50/50', 0, 0, 0, 'fresh', 'poultry', '', '', 'kilo'),
('Turkey', 0, 0, 0, 'fresh', 'poultry', '', '', 'kilo'),
('1.3 Chickens B/Shere', 0, 0, 0, 'fresh', 'poultry', '', '', 'kilo'),

('Sliced Turkey', 0, 0, 0, 'dry', 'poultry', '', '', 'pack'),

('Sliced Beef', 0, 0, 0, 'dry', 'beef', '', '', 'pack'),
('Sliced Corn Beef', 0, 0, 0, 'dry', 'beef', '', '', 'pack'),

('Haggis', 0, 0, 0, 'dry', 'pork', '', '', 'kilo'),
('Gammon', 0, 0, 0, 'dry', 'pork', '', '', 'kilo'),
('Whole Back Smoked', 0, 0, 0, 'dry', 'pork', '', '', 'kilo'),
('Whole Back Unsmoked', 0, 0, 0, 'dry', 'pork', '', '', 'kilo'),
('Unsmoked Back Bacon', 0, 0, 0, 'dry', 'pork', '', '', 'kilo'),
('Unsmoked Streaky', 0, 0, 0, 'dry', 'pork', '', '', 'kilo'),
('Smoked Streaky', 0, 0, 0, 'dry', 'pork', '', '', 'kilo'),
('Fresh Cumberland 8s', 0, 0, 0, 'dry', 'pork', '', '', 'kilo'),
('Fresh Cumberland 6s', 0, 0, 0, 'dry', 'pork', '', '', 'kilo'),

('Diced Venison', 0, 0, 0, 'fresh', 'deer', '', '', 'kilo'),

('3/8 Chips', 0, 0, 0, 'frozen', 'veg', '', '', 'case'),
('Steakhouse Chips', 0, 0, 0, 'frozen', 'veg', '', '', 'case'),
('Crispy Chips', 0, 0, 0, 'frozen', 'veg', '', '', 'case'),
('Hash Browns', 0, 0, 0, 'frozen', 'veg', '', '', 'case'),
('Mash', 0, 0, 0, 'frozen', 'veg', '', '', 'case'),
('Garden Peas', 0, 0, 0, 'frozen', 'veg', '', '', 'case'),
('Sweetcorn', 0, 0, 0, 'frozen', 'veg', '', '', 'case'),
('Green Beans. SL', 0, 0, 0, 'frozen', 'veg', '', '', 'case'),
('Green Beans. Wh', 0, 0, 0, 'frozen', 'veg', '', '', 'case'),
('Broccoli', 0, 0, 0, 'frozen', 'veg', '', '', 'case'),
('Mix Veg', 0, 0, 0, 'frozen', 'veg', '', '', 'case'),
('Button Sprouts', 0, 0, 0, 'frozen', 'veg', '', '', 'case'),
('Cauliflower', 0, 0, 0, 'frozen', 'veg', '', '', 'case'),
('Baby Carrots', 0, 0, 0, 'frozen', 'veg', '', '', 'case'),

('Battered Cod 4-5oz', 0, 0, 0, 'frozen', 'fish', '', '', 'case'),
('Breaded Cod 4-5oz', 0, 0, 0, 'frozen', 'fish', '', '', 'case'),
('Battered Cod 8-10oz', 0, 0, 0, 'frozen', 'fish', '', '', 'case'),
('Fish Fingers', 0, 0, 0, 'frozen', 'fish', '', '', 'case'),
('Fish Cakes', 0, 0, 0, 'frozen', 'fish', '', '', 'case'),
('Wholetail Scampi', 0, 0, 0, 'frozen', 'fish', '', '', 'case'),
('Low Glaze Prawns', 0, 0, 0, 'frozen', 'fish', '', '', 'case'),
('Cod Sless Bless', 0, 0, 0, 'frozen', 'fish', '', '', 'case'),
('Salmon Fillets', 0, 0, 0, 'frozen', 'fish', '', '', 'case'),

('Pork 32s', 0, 0, 0, 'frozen', 'pork', '', '', 'case'),
('Pork 16', 0, 0, 0, 'frozen', 'pork', '', '', 'case'),
('Pork 8', 0, 0, 0, 'frozen', 'pork', '', '', 'case'),
('Pork 4', 0, 0, 0, 'frozen', 'pork', '', '', 'case'),
('Pork SS meat', 0, 0, 0, 'frozen', 'pork', '', '', 'case'),
('Cumberland 16s', 0, 0, 0, 'frozen', 'pork', '', '', 'case'),
('Cumberland 8s', 0, 0, 0, 'frozen', 'pork', '', '', 'case'),
('Best Cumberland 8s', 0, 0, 0, 'frozen', 'pork', '', '', 'case'),
('RSPCA 16s', 0, 0, 0, 'frozen', 'pork', '', '', 'case'),
('RSPCA 8s', 0, 0, 0, 'frozen', 'pork', '', '', 'case'),
('Porkys SausageMeat', 0, 0, 0, 'frozen', 'pork', '', '', 'case'),

('Poultry 8s', 0, 0, 0, 'frozen', 'poultry', '', '', 'case'),
('Poultry 8s HALAL', 0, 0, 0, 'frozen', 'poultry', '', '', 'case'),
('R/Tr 50/50 Chicken', 0, 0, 0, 'frozen', 'poultry', '', '', 'case'),
('Chicken Nuggets', 0, 0, 0, 'frozen', 'poultry', '', '', 'case'),
('D. Cooked Chicken', 0, 0, 0, 'frozen', 'poultry', '', '', 'case'),
('Goujon Brd S/f', 0, 0, 0, 'frozen', 'poultry', '', '', 'case'),
('Goujon Brd H/S', 0, 0, 0, 'frozen', 'poultry', '', '', 'case'),
('Brd Chicken Fillet', 0, 0, 0, 'frozen', 'poultry', '', '', 'case'),

('Beef 8s', 0, 0, 0, 'frozen', 'beef', '', '', 'case'),
('R/Tr Meatballs', 0, 0, 0, 'frozen', 'beef', '', '', 'case'),
('DB Burgers 4oz', 0, 0, 0, 'frozen', 'beef', '', '', 'case'),
('R/Tr Burgers 4oz', 0, 0, 0, 'frozen', 'beef', '', '', 'case'),
('R/Tr Burgers 2oz', 0, 0, 0, 'frozen', 'beef', '', '', 'case'),
('R/Tr Minced Beef', 0, 0, 0, 'frozen', 'beef', '', '', 'case'),
('Porkys Minced Beef', 0, 0, 0, 'frozen', 'beef', '', '', 'case'),

('Grated Mix', 0, 0, 0, 'dry', 'dairy', '', '', 'case'),
('Grated Mature', 0, 0, 0, 'dry', 'dairy', '', '', 'case'),
('Grated Mild', 0, 0, 0, 'dry', 'dairy', '', '', 'case'),
('Grated Mozz', 0, 0, 0, 'dry', 'dairy', '', '', 'case'),
('Grated Mozz/Ch', 0, 0, 0, 'dry', 'dairy', '', '', 'case'),
('Grated Red', 0, 0, 0, 'dry', 'dairy', '', '', 'case'),
('5kg Mature', 0, 0, 0, 'dry', 'dairy', '', '', 'case'),
('5kg MILD', 0, 0, 0, 'dry', 'dairy', '', '', 'case'),

('Baileys Grated mild White Cheese 2kg', 0, 0, 0, 'dry', 'midland', '', '', 'bag'),
('Stilton Blue 1/4 1st Grade 2kg', 0, 0, 0, 'dry', 'midland', '', '', 'kilo'),
('Brie 60% 1kg - Ma Cremiere', 0, 0, 0, 'dry', 'midland', '', '', 'bag'),
('Mature Cheddar 5kg Chase Farm', 0, 0, 0, 'dry', 'midland', '', '', 'kilo'),
('Grated Mature 2kg (AXO15) Chase Farm', 0, 0, 0, 'dry', 'midland', '', '', 'bag'),
('Grana Padano PDO 1kg (', 0, 0, 0, 'dry', 'midland', '', '', 'kilo'),
('Halloumi 250gm', 0, 0, 0, 'dry', 'midland', '', '', 'bag'),
('Black Pudding Stick 1.36kg Oakwell', 0, 0, 0, 'dry', 'midland', '', '', 'bag'),
('Oakvale Frozen Faggots (1x15)', 0, 0, 0, 'dry', 'midland', '', '', 'bag'),
('Danish Salami - Qualitops 1.8kg', 0, 0, 0, 'dry', 'midland', '', '', 'bag'),
('French Style Garlic Stick 1.36kg', 0, 0, 0, 'dry', 'midland', '', '', 'bag'),
('MP Chorizo Stick Extra Mild 1.5kg', 0, 0, 0, 'dry', 'midland', '', '', 'kilo'),
('Pancetta Tesa - San Carlo', 0, 0, 0, 'dry', 'midland', '', '', 'kilo'),
('Tomato Paste 850 ml', 0, 0, 0, 'dry', 'midland', '', '', 'bag'),
('Ardennes Pate 1kg', 0, 0, 0, 'dry', 'midland', '', '', 'bag'),
('Cooked Diced Chicken', 0, 0, 0, 'dry', 'midland', '', '', 'bag'),
('Grand Mere Brussels Pate Log 1kg', 0, 0, 0, 'dry', 'midland', '', '', 'bag'),
('Tuna Chunks/Brine (Parkdale) 1.7kg', 0, 0, 0, 'dry', 'midland', '', '', 'bag'),
('Mission Plane Tortilla (10")25x18x4', 0, 0, 0, 'dry', 'midland', '', '', 'case'),
('Oakvale Scotch Eggs', 0, 0, 0, 'dry', 'midland', '', '', 'bag'),
('King Size Sausage Rolls', 0, 0, 0, 'dry', 'midland', '', '', 'case'),
('Chicken & Mushroom Pie', 0, 0, 0, 'dry', 'midland', '', '', 'case'),
('Large Pastry', 0, 0, 0, 'dry', 'midland', '', '', 'case'),
('Gala Pork Pie with Egg', 0, 0, 0, 'dry', 'midland', '', '', 'case'),
('TCM Small Pork Pies x12', 0, 0, 0, 'dry', 'midland', '', '', 'case'),
('Saveloys 4.08kg (36) - Tasty Bake', 0, 0, 0, 'dry', 'midland', '', '', 'case'),
('St Nicholas Baked Beans 6 x 2.65kg', 0, 0, 0, 'dry', 'midland', '', '', 'case'),
('Bella Napoli Plum Tomatoes 6x2.5kg', 0, 0, 0, 'dry', 'midland', '', '', 'case'),
('Bella Napoli Chopped Tomatoes 6x2.50kg', 0, 0, 0, 'dry', 'midland', '', '', 'case'),
('T/S (7002) White Baguette 30 x 135gm', 0, 0, 0, 'dry', 'midland', '', '', 'case'),
('P/B (7009) Malted Wheat Baguette 30x135', 0, 0, 0, 'dry', 'midland', '', '', 'case'),
('Chase Farm Sliced 100% Beef ', 0, 0, 0, 'dry', 'midland', '', '', 'bag'),
('Chase Farm Sliced Bentley Roast Turkey', 0, 0, 0, 'dry', 'midland', '', '', 'bag'),
('Chase Farm Sliced 92% Chicken', 0, 0, 0, 'dry', 'midland', '', '', 'bag'),
('Sliced Pancetta Affumicata', 0, 0, 0, 'dry', 'midland', '', '', 'bag'),
('Sliced Proscuitto 80g', 0, 0, 0, 'dry', 'midland', '', '', 'bag'),
('Sliced Proscuitto 500g', 0, 0, 0, 'dry', 'midland', '', '', 'bag'),
('CHASE FARM Sliced Corn Beef 500g', 0, 0, 0, 'dry', 'midland', '', '', 'bag'),
('CHASE FARM Sliced Gamman Ham 500g', 0, 0, 0, 'dry', 'midland', '', '', 'bag'),
('Sliced Chorizo Mild 250gm', 0, 0, 0, 'dry', 'midland', '', '', 'bag'),
('Mini BBQ Chorizo', 0, 0, 0, 'dry', 'midland', '', '', 'bag'),
('5kg Mild', 0, 0, 0, 'dry', 'midland', '', '', 'case'),
('Hash Browns', 0, 0, 0, 'dry', 'midland', '', '', 'case'),
('Liver sausage 1kg', 0, 0, 0, 'dry', 'midland', '', '', 'bag'),
('2.5kgs Mixed Veg', 0, 0, 0, 'dry', 'midland', '', '', 'bag'),
('2.5kgs Garden Peas', 0, 0, 0, 'dry', 'midland', '', '', 'bag'),
('Tins of Sweetcorn', 0, 0, 0, 'dry', 'midland', '', '', 'bag')]

if __name__ == "__main__":
    insert_to_database()
