SET local check_function_bodies = off;

CREATE EXTENSION "pgjwt" SCHEMA "extensions";

CREATE SEQUENCE "public"."products_id_seq" AS integer INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1 NO CYCLE;

CREATE SEQUENCE "public"."stock_takes_id_seq" AS integer INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1 NO CYCLE;

CREATE TABLE "public"."butchers_lists" (
  "id"           bigint                      GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "created_at"   timestamp without time zone NOT NULL DEFAULT now(),
  "updated_at"   timestamp without time zone,
  "date"         timestamp without time zone NOT NULL,
  "data"         jsonb                       NOT NULL,
  "refreshed_at" timestamp with time zone,
  CONSTRAINT "butchers_lists_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."butchers_lists"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."conversion_items" (
  "id"            uuid                     NOT NULL DEFAULT gen_random_uuid(),
  "created_at"    timestamp with time zone NOT NULL DEFAULT now(),
  "product_id"    integer,
  "quantity"      real,
  "type"          text,
  "conversion_id" uuid,
  "end_point"     text,
  CONSTRAINT "conversion_items_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."conversion_items"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."conversions" (
  "id"              uuid                     NOT NULL DEFAULT gen_random_uuid(),
  "created_at"      timestamp with time zone NOT NULL DEFAULT now(),
  "input_product"   bigint,
  "output_products" jsonb,
  "status"          text,
  "completed_at"    timestamp with time zone,
  "created_by"      uuid,
  CONSTRAINT "conversions_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."conversions"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."deliveries" (
  "created_at"          timestamp with time zone NOT NULL DEFAULT now(),
  "product"             integer,
  "quantity"            integer,
  "receipt_image"       text,
  "notes"               text,
  "id"                  uuid                     NOT NULL DEFAULT gen_random_uuid(),
  "vehicle_temperature" text,
  "driver_name"         text,
  "license_plate"       text,
  "created_by"          uuid,
  "batch_code"          integer,
  "origin"              text,
  "product_temperature" text,
  "kill_date"           timestamp with time zone,
  "use_by"              timestamp with time zone,
  "red_tractor"         boolean,
  "rspca"               boolean,
  "slaughter_number"    text,
  "cut_number"          text,
  "organic_assured"     boolean,
  "supplier"            text,
  "date"                text,
  CONSTRAINT "deliveries_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."deliveries"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."duke_york_prices" (
  "id"         bigint                      GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "created_at" timestamp with time zone    NOT NULL DEFAULT now(),
  "date"       timestamp without time zone,
  "data"       json,
  "active"     boolean                     NOT NULL DEFAULT true,
  CONSTRAINT "duke_york_prices_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."duke_york_prices"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."products" (
  "id"               integer NOT NULL DEFAULT nextval('public.products_id_seq'::regclass),
  "name"             text    NOT NULL,
  "cost"             real,
  "stock_count"      real,
  "product_value"    real,
  "stock_category"   text    NOT NULL,
  "product_category" text,
  "sage_code"        text,
  "supplier"         text,
  "sold_as"          text    NOT NULL,
  CONSTRAINT "products_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."products"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."reports" (
  "id"          bigint                   GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "created_at"  timestamp with time zone NOT NULL DEFAULT now(),
  "name"        text,
  "products"    jsonb,
  "created_by"  bigint,
  "description" text,
  "customers"   jsonb,
  CONSTRAINT "reports_id_key" UNIQUE (id),
  CONSTRAINT "reports_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."reports"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."stock_movement" (
  "id"           uuid                     NOT NULL DEFAULT gen_random_uuid(),
  "created_at"   timestamp with time zone NOT NULL DEFAULT now(),
  "product"      bigint,
  "quantity"     double precision,
  "type"         text,
  "reference_id" uuid,
  CONSTRAINT "stock_movement_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."stock_movement"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."stock_sold_report" (
  "id"         bigint                   GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "created_at" timestamp with time zone NOT NULL DEFAULT now(),
  "date"       timestamp with time zone,
  "data"       jsonb,
  "created_by" bigint,
  "updated_at" timestamp with time zone,
  CONSTRAINT "stock_sold_report_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."stock_sold_report"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."stock_takes" (
  "id"               integer                     NOT NULL DEFAULT nextval('public.stock_takes_id_seq'::regclass),
  "date"             timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "take"             jsonb                       NOT NULL,
  "product_category" text                        NOT NULL,
  "date_added"       timestamp without time zone NOT NULL DEFAULT now(),
  "created_by"       uuid,
  CONSTRAINT "stock_takes_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."stock_takes"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."users" (
  "id"          uuid                     NOT NULL DEFAULT gen_random_uuid(),
  "created_at"  timestamp with time zone NOT NULL DEFAULT now(),
  "name"        text,
  "department"  text,
  "permissions" jsonb,
  "email"       text,
  "approved"    boolean                  NOT NULL DEFAULT false,
  "admin"       boolean                  DEFAULT false,
  "passcode"    integer,
  CONSTRAINT "users_passcode_key" UNIQUE (passcode),
  CONSTRAINT "users_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."users"
  ENABLE ROW LEVEL SECURITY;

ALTER SEQUENCE "public"."products_id_seq" OWNED BY "public"."products"."id";

ALTER SEQUENCE "public"."stock_takes_id_seq" OWNED BY "public"."stock_takes"."id";

CREATE OR REPLACE FUNCTION public.get_current_user()
  RETURNS TABLE (
    id       uuid,
    email    text,
    name     text,
    passcode integer
  )
  LANGUAGE plpgsql
  SECURITY DEFINER
  AS $function$
BEGIN
  RETURN QUERY
  SELECT u.id, u.email, u.name, u.passcode
  FROM public.users u
  WHERE u.passcode = current_setting('app.current_passcode', true)::integer
  AND u.approved = true;
END;
$function$;

CREATE OR REPLACE FUNCTION public.set_session_passcode (
  passcode text
)
  RETURNS void
  LANGUAGE plpgsql
  SECURITY DEFINER
  AS $function$
BEGIN
  PERFORM set_config('app.current_passcode', passcode, false);
END;
$function$;

CREATE POLICY "Allow access to conversion_items for authenticated and passcode" ON "public"."conversion_items"
  FOR ALL
  TO PUBLIC
  USING (((auth.uid() IS NOT NULL) OR (EXISTS ( SELECT 1
   FROM public.users
  WHERE ((users.passcode = (current_setting('app.current_passcode'::text, true))::integer) AND (users.approved = true))))))
  WITH CHECK (((auth.uid() IS NOT NULL) OR (EXISTS ( SELECT 1
   FROM public.users
  WHERE ((users.passcode = (current_setting('app.current_passcode'::text, true))::integer) AND (users.approved = true))))));

CREATE POLICY "Enable insert for authenticated users only" ON "public"."conversion_items"
  FOR INSERT
  TO "authenticated"
  WITH CHECK (true);

CREATE POLICY "Enable read access for all users" ON "public"."conversion_items"
  FOR SELECT
  TO PUBLIC
  USING (true);

CREATE POLICY "Allow access to conversions for authenticated and passcode user" ON "public"."conversions"
  FOR ALL
  TO PUBLIC
  USING (((auth.uid() IS NOT NULL) OR (EXISTS ( SELECT 1
   FROM public.users
  WHERE ((users.passcode = (current_setting('app.current_passcode'::text, true))::integer) AND (users.approved = true))))));

CREATE POLICY "Allow users to update rows" ON "public"."conversions"
  FOR UPDATE
  TO "authenticated"
  USING (true);

CREATE POLICY "Enable insert for authenticated users only" ON "public"."conversions"
  FOR INSERT
  TO "anon", "authenticated"
  WITH CHECK (true);

CREATE POLICY "Enable read access for all users" ON "public"."conversions"
  FOR SELECT
  TO PUBLIC
  USING (true);

CREATE POLICY "Enable insert for authenticated users only" ON "public"."deliveries"
  FOR INSERT
  TO "authenticated"
  WITH CHECK (true);

CREATE POLICY "Enable read access for all users" ON "public"."deliveries"
  FOR SELECT
  TO PUBLIC
  USING (true);

CREATE POLICY "Enable read access for all users" ON "public"."products"
  FOR SELECT
  TO PUBLIC
  USING (true);

CREATE POLICY "Enable update for users based " ON "public"."products"
  FOR UPDATE
  TO "authenticated"
  USING (true)
  WITH CHECK (true);

CREATE POLICY "Enable insert for authenticated users only" ON "public"."stock_takes"
  FOR INSERT
  TO "authenticated"
  WITH CHECK (true);

CREATE POLICY "Enable read access for all users" ON "public"."stock_takes"
  FOR SELECT
  TO PUBLIC
  USING (true);

CREATE POLICY "Enable read access for all users" ON "public"."users"
  FOR SELECT
  TO PUBLIC
  USING (true);

CREATE POLICY "Users can read via email auth" ON "public"."users"
  FOR SELECT
  TO PUBLIC
  USING (((auth.uid() IS NOT NULL) AND (email = auth.email())));

CREATE POLICY "Users can read via passcode auth" ON "public"."users"
  FOR SELECT
  TO PUBLIC
  USING (((auth.uid() IS NULL) AND (passcode IS NOT NULL) AND (passcode = (current_setting('app.current_passcode'::text, true))::integer) AND (approved = true)));

COMMENT ON EXTENSION "pgjwt" IS 'JSON Web Token API for Postgresql';

GRANT EXECUTE ON FUNCTION "public"."get_current_user"() TO PUBLIC, "anon", "authenticated", "postgres", "service_role";

GRANT EXECUTE ON FUNCTION "public"."set_session_passcode"(text) TO PUBLIC, "anon", "authenticated", "postgres", "service_role";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."products_id_seq" TO "anon", "authenticated", "postgres", "service_role";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."stock_takes_id_seq" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."butchers_lists" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."conversion_items" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."conversions" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."deliveries" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."duke_york_prices" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."products" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."reports" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."stock_movement" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."stock_sold_report" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."stock_takes" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."users" TO "anon", "authenticated", "postgres", "service_role";

