name: Build and Release

permissions:
  contents: write
  actions: write # Added permission for deleting artifacts

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version (e.g., v1.0.0)"
        required: true

jobs:
  cleanup-artifacts:
    runs-on: ubuntu-latest
    steps:
      - name: Delete old artifacts
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const repo = context.repo;
            console.log(`Cleaning up artifacts for ${repo.owner}/${repo.repo}`);
            
            // Get list of all artifacts
            const artifacts = await github.rest.actions.listArtifactsForRepo({
              owner: repo.owner,
              repo: repo.repo
            });
            
            // Keep only the 5 most recent artifacts
            const artifactsToDelete = artifacts.data.artifacts.slice(1);
            
            // Delete old artifacts
            for (const artifact of artifactsToDelete) {
              console.log(`Deleting artifact ${artifact.name} (ID: ${artifact.id})`);
              await github.rest.actions.deleteArtifact({
                owner: repo.owner,
                repo: repo.repo,
                artifact_id: artifact.id
              });
            }

  build-macos:
    needs: cleanup-artifacts
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install PostgreSQL (Required for psycopg2)
        run: |
          brew update
          brew install postgresql
          echo "PATH=$(brew --prefix postgresql)/bin:$PATH" >> $GITHUB_ENV

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyqt5
          pip install psycopg2-binary
          pip install requests
          pip install PyQtWebEngine
          pip install pyinstaller

      - name: Debug dependencies
        run: python -c "import sys; print(sys.path); import psycopg2; import requests; print('All dependencies imported successfully!')"

      - name: Build executable
        run: pyinstaller main.spec

      - name: Upload executable as artifact
        uses: actions/upload-artifact@v4
        with:
          name: ManageMeStockM
          path: dist/ManageMeStock

  build-windows:
    needs: cleanup-artifacts
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyqt5
          pip install psycopg2-binary
          pip install requests
          pip install PyQtWebEngine
          pip install pyinstaller

      - name: Debug dependencies
        run: python -c "import sys; print(sys.path); import psycopg2; import requests; print('All dependencies imported successfully!')"

      - name: Build executable
        run: pyinstaller main.spec

      - name: Upload executable as artifact
        uses: actions/upload-artifact@v4
        with:
          name: ManageMeStockW
          path: dist/ManageMeStock.exe

  release:
    needs: [build-windows, build-macos]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download Windows artifact
        uses: actions/download-artifact@v4
        with:
          name: ManageMeStockW
          path: dist

      - name: Download macOS artifact
        uses: actions/download-artifact@v4
        with:
          name: ManageMeStockM
          path: dist

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/ManageMeStock.exe
            dist/ManageMeStock
          tag_name: ${{ github.event.inputs.version }}
          release_name: Release ${{ github.event.inputs.version }}
          draft: false
          prerelease: false
