name: Build and Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version (e.g., v1.0.0)"
        required: true

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyqt5 psycopg2-binary requests PyQtWebEngine pyinstaller

      - name: Build executable
        run: pyinstaller main.spec

      - name: Upload Windows executable
        uses: actions/upload-artifact@v4
        with:
          name: ManageMeStock-Windows
          path: dist/ManageMeStock.exe

  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyqt5 psycopg2-binary requests PyQtWebEngine pyinstaller

      - name: Build macOS app
        run: pyinstaller --windowed --name ManageMeStock main.py

      - name: Upload macOS app
        uses: actions/upload-artifact@v4
        with:
          name: ManageMeStock-Mac
          path: dist/ManageMeStock.app

  release:
    needs: [build-windows, build-macos]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download Windows artifact
        uses: actions/download-artifact@v4
        with:
          name: ManageMeStock
          path: dist/

      - name: Download macOS artifact
        uses: actions/download-artifact@v4
        with:
          name: ManageMeStock
          path: dist/

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/ManageMeStock.exe
            dist/ManageMeStock.app
          tag_name: ${{ github.event.inputs.version }}
          release_name: Release ${{ github.event.inputs.version }}
          draft: false
          prerelease: false
