name: Build & Deploy

on:
  workflow_dispatch:  # Allows manual triggering of deployment

jobs:
  build:
    runs-on: ubuntu-latest  # Use macos-latest for Mac builds, windows-latest for Windows

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install Dependencies
        run: |
          pip install pyinstaller
          pip install -r requirements.txt  # Ensure dependencies are installed

      - name: Build Executable (Windows)
        if: runner.os == 'Windows'
        run: pyinstaller --onefile --name YourApp main.py

      - name: Build Executable (macOS)
        if: runner.os == 'macOS'
        run: pyinstaller --onefile --windowed --name YourApp main.py

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: YourApp
          path: dist/YourApp*

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: YourApp
          path: dist/

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v1.0.${{ github.run_number }}
          name: Release v1.0.${{ github.run_number }}
          body: "New release of YourApp"
          draft: false
          prerelease: false
          files: dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
