name: Build Windows Executable

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyqt5
          pip install psycopg2-binary
          pip install requests
          pip install pyinstaller

      - name: Debug dependencies
        run: python -c "import sys; print(sys.path); import psycopg2; import requests; print('All dependencies imported successfully!')"

      - name: Build executable using spec file
        run: |
          pyinstaller main.spec

      - name: Upload executable as artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-executable
          path: dist/main.exe

      - name: Upload build logs
        uses: actions/upload-artifact@v4
        with:
          name: pyinstaller-build-logs
          path: build/

      - name: Upload PyInstaller warnings
        uses: actions/upload-artifact@v4
        with:
          name: pyinstaller-warnings
          path: build/main/warn-main.txt
