name: Build Executable for macOS & Windows

on:
  workflow_dispatch:

jobs:
  build-macos:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install PostgreSQL (Required for psycopg2)
        run: |
          brew update
          brew install postgresql
          echo "PATH=$(brew --prefix postgresql)/bin:$PATH" >> $GITHUB_ENV

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyqt5
          pip install psycopg2-binary
          pip install requests
          pip install PyQtWebEngine
          pip install pyinstaller

      - name: Debug dependencies
        run: python -c "import sys; print(sys.path); import psycopg2; import requests; print('All dependencies imported successfully!')"

      - name: Build executable
        run: pyinstaller main.spec

      - name: Upload executable as artifact
        uses: actions/upload-artifact@v4
        with:
          name: macos-executable
          path: dist/ManageMeStock

  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyqt5
          pip install psycopg2-binary
          pip install requests
          pip install PyQtWebEngine
          pip install pyinstaller

      - name: Debug dependencies
        run: python -c "import sys; print(sys.path); import psycopg2; import requests; print('All dependencies imported successfully!')"

      - name: Build executable
        run: pyinstaller main.spec

      - name: Upload executable as artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-executable
          path: dist/ManageMeStock.exe
